docker_extensions = {
    ".dockerfile", ".dockerignore", ".dockerignore.local", ".dockerignore.global", ".dockerignore.user",
    ".dockerignore.system", ".dockerignore.example", ".dockerignore.sample", ".dockerignore.template",
    ".dockerignore.backup", ".dockerignore.old", ".dockerignore.save", ".dockerignore.enc",
    ".dockerignore.encrypted", ".dockerignore.crypt", ".dockerignore.secure", ".dockerignore.default",
    ".dockerignore.custom", ".dockerignore.override", ".dockerignore.extra", ".dockerignore.additional",
    ".dockerignore.supplemental", ".dockerignore.all", ".dockerignore.full", ".dockerignore.partial",
    ".dockerignore.minimal", ".dockerignore.extended", ".dockerignore.recommended", ".dockerignore.standard",
    ".dockerignore.optimal", ".docker-compose.yml", ".docker-compose.yaml", ".docker-compose.override.yml",
    ".docker-compose.override.yaml", ".docker-compose.local.yml", ".docker-compose.local.yaml",
    ".docker-compose.dev.yml", ".docker-compose.dev.yaml", ".docker-compose.prod.yml",
    ".docker-compose.prod.yaml", ".docker-compose.staging.yml", ".docker-compose.staging.yaml",
    ".docker-compose.test.yml", ".docker-compose.test.yaml", ".docker-compose.ci.yml",
    ".docker-compose.ci.yaml", ".docker-compose.backup.yml", ".docker-compose.backup.yaml",
    ".docker-compose.old.yml", ".docker-compose.old.yaml", ".docker-compose.save.yml",
    ".docker-compose.save.yaml", ".docker-compose.enc.yml", ".docker-compose.enc.yaml",
    ".docker-compose.encrypted.yml", ".docker-compose.encrypted.yaml", ".docker-compose.crypt.yml",
    ".docker-compose.crypt.yaml", ".docker-compose.secure.yml", ".docker-compose.secure.yaml",
    ".docker-compose.default.yml", ".docker-compose.default.yaml", ".docker-compose.example.yml",
    ".docker-compose.example.yaml", ".docker-compose.sample.yml", ".docker-compose.sample.yaml",
    ".docker-compose.template.yml", ".docker-compose.template.yaml", ".docker-compose.override.yml.bak",
    ".docker-compose.override.yaml.bak", ".docker-compose.*.yml", ".docker-compose.*.yaml",
    ".docker-compose.*.yml.bak", ".docker-compose.*.yaml.bak", ".docker-compose.yml.old",
    ".docker-compose.yaml.old", ".docker-compose.yml.save", ".docker-compose.yaml.save",
    ".docker-compose.yml.backup", ".docker-compose.yaml.backup", ".docker-compose.yml.enc",
    ".docker-compose.yaml.enc", ".docker-compose.yml.encrypted", ".docker-compose.yaml.encrypted",
    ".docker-compose.yml.crypt", ".docker-compose.yaml.crypt", ".docker-compose.yml.secure",
    ".docker-compose.yaml.secure", ".docker-compose.override.yml.old", ".docker-compose.override.yaml.old",
    ".docker-compose.override.yml.save", ".docker-compose.override.yaml.save",
    ".docker-compose.override.yml.backup", ".docker-compose.override.yaml.backup",
    ".docker-compose.override.yml.enc", ".docker-compose.override.yaml.enc",
    ".docker-compose.override.yml.encrypted", ".docker-compose.override.yaml.encrypted",
    ".docker-compose.override.yml.crypt", ".docker-compose.override.yaml.crypt",
    ".docker-compose.override.yml.secure", ".docker-compose.override.yaml.secure",
    ".containerignore", ".containerignore.local", ".containerignore.global", ".containerignore.user",
    ".containerignore.system", ".containerignore.example", ".containerignore.sample",
    ".containerignore.template", ".containerignore.backup", ".containerignore.old",
    ".containerignore.save", ".containerignore.enc", ".containerignore.encrypted",
    ".containerignore.crypt", ".containerignore.secure", ".containerignore.default",
    ".containerignore.custom", ".containerignore.override", ".containerignore.extra",
    ".containerignore.additional", ".containerignore.supplemental", ".containerignore.all",
    ".containerignore.full", ".containerignore.partial", ".containerignore.minimal",
    ".containerignore.extended", ".containerignore.recommended", ".containerignore.standard",
    ".containerignore.optimal", ".docker", 
}
