extensions = {
    ".pem", ".key", ".pub", ".ppk", ".ssh", ".openssh", ".id_rsa", ".id_dsa",
    ".id_ecdsa", ".id_ecdsa_sk", ".id_ed25519", ".id_ed25519_sk", ".id_xmss", 
    ".identity", ".identity.pub", ".private_key", ".private", ".priv", ".secret",
    ".ssh_host_rsa_key", ".ssh_host_dsa_key", ".ssh_host_ecdsa_key", 
    ".ssh_host_ed25519_key", ".ssh_host_key", ".authorized_keys", ".authorized_keys2",
    ".known_hosts", ".known_hosts2", ".ssh_config", ".ssh_config.d", ".sshd_config",
    ".ssh2", ".ssh2_config", ".putty", ".putty_config", ".pageant", ".pageant.ppk",
    ".ssh_known_hosts", ".ssh_authorized_keys", ".ssh_authorized_keys2",
    ".ssh_private_key", ".ssh_public_key", ".ssh_session_key", ".ssh_session_keys",
    ".ssh_agent", ".ssh_agent_sock", ".ssh_control", ".ssh_control_master",
    ".ssh_environment", ".ssh_rc", ".ssh_askpass", ".ssh_askpass.conf",
    ".ssh_known_hosts.old", ".ssh_authorized_keys.old", ".ssh_host_ecdsa_key.pub",
    ".ssh_host_ed25519_key.pub", ".ssh_host_rsa_key.pub", ".ssh_host_dsa_key.pub",
    ".ssh_host_key.pub", ".ssh2_hostkey", ".ssh2_hostkey.pub", ".ssh2_private",
    ".ssh2_public", ".ssh2_config.d", ".ssh2_known_hosts", ".ssh2_authorized_keys",
    ".putty_private_key", ".putty_public_key", ".putty_session", ".putty_sessions",
    ".putty_known_hosts", ".putty_random_seed", ".putty_rnd", ".putty_sav",
    ".pageant_key", ".pageant_keys", ".pageant_private", ".pageant_public",
    ".winscp", ".winscp_key", ".winscp_private", ".winscp_public", ".winscp_session",
    ".winscp_config", ".winscp.ini", ".filezilla", ".filezilla_key", ".filezilla_private",
    ".filezilla_public", ".filezilla.xml", ".filezilla.xml.bak", ".filezilla.xml.old",
    ".filezilla.xml.default", ".filezilla.xml.example", ".filezilla.xml.sample",
    ".filezilla.xml.template", ".filezilla.xml.backup", ".filezilla.xml.save",
    ".filezilla.xml.encrypted", ".filezilla.xml.enc", ".filezilla.xml.crypt",
    ".filezilla.xml.secure", ".filezilla.xml.key", ".filezilla.xml.key.enc",
    ".filezilla.xml.key.crypt", ".filezilla.xml.key.secure", ".filezilla.xml.key.backup",
    ".filezilla.xml.key.save", ".filezilla.xml.key.old", ".filezilla.xml.key.default",
    ".crt", ".cer", ".cert", ".der", ".p12", ".pfx", ".p7b", ".p7c",
    ".p7r", ".p7s", ".p8", ".pkcs7", ".pkcs8", ".pkcs12", ".p10",
    ".csr", ".crl", ".sst", ".spc", ".jks", ".keystore", ".truststore",
    ".bks", ".ubr", ".ce", ".crtx", ".crt64", ".crt32", ".ovpn",
    ".cacert", ".ca-bundle", ".ca-certificates", ".certificate", ".certificates",
    ".chain", ".fullchain", ".privkey", ".certkey", ".combined", ".bundle",
    ".intermediate", ".intermediate.crt", ".root", ".root.crt", ".issuer",
    ".pem-key", ".pem-crt", ".key-pem", ".crt-pem", ".ssl-cert", ".ssl-key",
    ".tls", ".tls-cert", ".tls-key", ".x509", ".x509-cert", ".x509-key",
    ".ca", ".ca-key", ".ca-crt", ".ca-pem", ".ca-der", ".ca-p12", ".ca-pfx",
    ".ca-chain", ".ca-chain.crt", ".ca-chain.pem", ".ca-chain.der", ".ca-chain.p12",
    ".ca-chain.pfx", ".ca-chain.jks", ".ca-chain.bks", ".ca-chain.keystore",
    ".ca-chain.truststore", ".ca-bundle.crt", ".ca-bundle.pem", ".ca-bundle.der",
    ".ca-bundle.p12", ".ca-bundle.pfx", ".ca-bundle.jks", ".ca-bundle.bks",
    ".ca-certificates.crt", ".ca-certificates.pem", ".ca-certificates.der",
    ".ca-certificates.p12", ".ca-certificates.pfx", ".ca-certificates.jks",
    ".ca-certificates.bks", ".ca-certificates.keystore", ".ca-certificates.truststore",
    ".intermediate-ca", ".intermediate-ca.crt", ".intermediate-ca.pem",
    ".intermediate-ca.der", ".intermediate-ca.p12", ".intermediate-ca.pfx",
    ".intermediate-ca.jks", ".intermediate-ca.bks", ".intermediate-ca.keystore",
    ".intermediate-ca.truststore", ".root-ca", ".root-ca.crt", ".root-ca.pem",
    ".root-ca.der", ".root-ca.p12", ".root-ca.pfx", ".root-ca.jks", ".root-ca.bks",
    ".root-ca.keystore", ".root-ca.truststore", ".issuer-ca", ".issuer-ca.crt",
    ".issuer-ca.pem", ".issuer-ca.der", ".issuer-ca.p12", ".issuer-ca.pfx",
    ".issuer-ca.jks", ".issuer-ca.bks", ".issuer-ca.keystore", ".issuer-ca.truststore",
    ".cert-chain", ".cert-chain.crt", ".cert-chain.pem", ".cert-chain.der",
    ".cert-chain.p12", ".cert-chain.pfx", ".cert-chain.jks", ".cert-chain.bks",
    ".cert-chain.keystore", ".cert-chain.truststore", ".fullchain.crt",
    ".fullchain.pem", ".fullchain.der", ".fullchain.p12", ".fullchain.pfx",
    ".fullchain.jks", ".fullchain.bks", ".fullchain.keystore", ".fullchain.truststore",
    ".privkey.crt", ".privkey.pem", ".privkey.der", ".privkey.p12", ".privkey.pfx",
    ".privkey.jks", ".privkey.bks", ".privkey.keystore", ".privkey.truststore",
    ".certkey.crt", ".certkey.pem", ".certkey.der", ".certkey.p12", ".certkey.pfx",
    ".certkey.jks", ".certkey.bks", ".certkey.keystore", ".certkey.truststore",
    ".combined.crt", ".combined.pem", ".combined.der", ".combined.p12",
    ".combined.pfx", ".combined.jks", ".combined.bks", ".combined.keystore",
    ".combined.truststore", ".bundle.crt", ".bundle.pem", ".bundle.der",
    ".bundle.p12", ".bundle.pfx", ".bundle.jks", ".bundle.bks", ".bundle.keystore",
    ".bundle.truststore", ".pkcs12.p12", ".pkcs12.pfx", ".pkcs12.jks", ".pkcs12.bks",
    ".pkcs12.keystore", ".pkcs12.truststore", ".pkcs8.key", ".pkcs8.pem",
    ".pkcs8.der", ".pkcs8.pkcs8", ".pkcs8.enc", ".pkcs8.encrypted",
    ".pkcs8.encrypted.key", ".pkcs8.encrypted.pem", ".pkcs8.encrypted.der",
    ".pkcs8.encrypted.pkcs8", ".pkcs8.enc", ".pkcs8.crypt", ".pkcs8.secure",
    ".pkcs8.backup", ".pkcs8.old", ".pkcs8.default", ".pkcs8.example",
    ".pkcs8.sample", ".pkcs8.template", ".pkcs8.key.enc", ".pkcs8.key.crypt",
    ".pkcs8.key.secure", ".pkcs8.key.backup", ".pkcs8.key.old", ".pkcs8.key.default",
    ".pkcs8.key.example", ".pkcs8.key.sample", ".pkcs8.key.template",
    ".openssl.key", ".openssl.crt", ".openssl.pem", ".openssl.der", ".openssl.p12",
    ".openssl.pfx", ".openssl.jks", ".openssl.bks", ".openssl.keystore",
    ".openssl.truststore", ".openssl.enc", ".openssl.encrypted", ".openssl.crypt",
    ".openssl.secure", ".openssl.backup", ".openssl.old", ".openssl.default",
    ".openssl.example", ".openssl.sample", ".openssl.template", ".openssl.key.enc",
    ".openssl.key.crypt", ".openssl.key.secure", ".openssl.key.backup",
    ".openssl.key.old", ".openssl.key.default", ".openssl.key.example",
    ".openssl.key.sample", ".openssl.key.template", ".ssl.key", ".ssl.crt",
    ".ssl.pem", ".ssl.der", ".ssl.p12", ".ssl.pfx", ".ssl.jks", ".ssl.bks",
    ".ssl.keystore", ".ssl.truststore", ".ssl.enc", ".ssl.encrypted", ".ssl.crypt",
    ".ssl.secure", ".ssl.backup", ".ssl.old", ".ssl.default", ".ssl.example",
    ".ssl.sample", ".ssl.template", ".tls.key", ".tls.crt", ".tls.pem", ".tls.der",
    ".tls.p12", ".tls.pfx", ".tls.jks", ".tls.bks", ".tls.keystore", ".tls.truststore",
    ".tls.enc", ".tls.encrypted", ".tls.crypt", ".tls.secure", ".tls.backup",
    ".tls.old", ".tls.default", ".tls.example", ".tls.sample", ".tls.template",
    ".x509.key", ".x509.crt", ".x509.pem", ".x509.der", ".x509.p12", ".x509.pfx",
    ".x509.jks", ".x509.bks", ".x509.keystore", ".x509.truststore", ".x509.enc",
    ".x509.encrypted", ".x509.crypt", ".x509.secure", ".x509.backup", ".x509.old",
    ".x509.default", ".x509.example", ".x509.sample", ".x509.template",
    ".ovpn", ".openvpn", ".vpn", ".wireguard", ".wg", ".conf", ".ipsec",
    ".strongswan", ".swanctl", ".ipsec.conf", ".ipsec.secrets", ".vpnconfig",
    ".openvpn-config", ".pcf", ".cscfg", ".vpnsettings", ".wireguard-config",
    ".wg-quick", ".wg0.conf", ".tinc", ".tinc.conf", ".tinc-up", ".tinc-down",
    ".openconnect", ".anyconnect", ".vpnc", ".vpnc.conf", ".fortinet",
    ".openvpn.key", ".openvpn.crt", ".openvpn.pem", ".openvpn.der", ".openvpn.p12",
    ".openvpn.pfx", ".openvpn.jks", ".openvpn.bks", ".openvpn.keystore",
    ".openvpn.truststore", ".openvpn.ca", ".openvpn.ca.crt", ".openvpn.ca.pem",
    ".openvpn.ca.der", ".openvpn.client", ".openvpn.client.crt", ".openvpn.client.key",
    ".openvpn.client.pem", ".openvpn.client.der", ".openvpn.client.p12",
    ".openvpn.client.pfx", ".openvpn.server", ".openvpn.server.crt",
    ".openvpn.server.key", ".openvpn.server.pem", ".openvpn.server.der",
    ".openvpn.server.p12", ".openvpn.server.pfx", ".openvpn.dh", ".openvpn.dh.pem",
    ".openvpn.dh.der", ".openvpn.dh.p12", ".openvpn.dh.pfx", ".openvpn.dh.jks",
    ".openvpn.dh.bks", ".openvpn.tls-auth", ".openvpn.tls-auth.key",
    ".openvpn.tls-auth.pem", ".openvpn.tls-auth.der", ".openvpn.tls-crypt",
    ".openvpn.tls-crypt.key", ".openvpn.tls-crypt.pem", ".openvpn.tls-crypt.der",
    ".openvpn.auth", ".openvpn.auth-file", ".openvpn.auth-file.txt",
    ".openvpn.auth-file.pass", ".openvpn.auth-file.password", ".openvpn.auth-file.creds",
    ".openvpn.auth-file.credentials", ".openvpn.auth-file.conf", ".openvpn.auth-file.config",
    ".openvpn.up", ".openvpn.down", ".openvpn.route-up", ".openvpn.ipchange",
    ".openvpn.client-connect", ".openvpn.client-disconnect", ".openvpn.learn-address",
    ".openvpn.tls-verify", ".openvpn.auth-user-pass-verify", ".openvpn.client-config-dir",
    ".openvpn.ccd", ".openvpn.ipp", ".openvpn.status", ".openvpn.log", ".openvpn.ovpn",
    ".wireguard.key", ".wireguard.priv", ".wireguard.pub", ".wireguard.private",
    ".wireguard.public", ".wireguard.psk", ".wireguard.preshared", ".wireguard.preshared.key",
    ".wireguard.preshared.psk", ".wireguard.preshared.secret", ".wireguard.preshared.secure",
    ".wireguard.preshared.enc", ".wireguard.preshared.encrypted", ".wireguard.preshared.crypt",
    ".wireguard.conf", ".wireguard.config", ".wireguard.wg", ".wireguard.wg-quick",
    ".wireguard.wg0", ".wireguard.wg0.conf", ".wireguard.wg1", ".wireguard.wg1.conf",
    ".wireguard.wg2", ".wireguard.wg2.conf", ".wireguard.wg3", ".wireguard.wg3.conf",
    ".wireguard.wg4", ".wireguard.wg4.conf", ".wireguard.wg5", ".wireguard.wg5.conf",
    ".wireguard.wg6", ".wireguard.wg6.conf", ".wireguard.wg7", ".wireguard.wg7.conf",
    ".wireguard.wg8", ".wireguard.wg8.conf", ".wireguard.wg9", ".wireguard.wg9.conf",
    ".wireguard.wg10", ".wireguard.wg10.conf", ".wireguard.allowed-ips",
    ".wireguard.allowed-ips.conf", ".wireguard.allowed-ips.txt", ".wireguard.allowed-ips.list",
    ".wireguard.peer", ".wireguard.peer.conf", ".wireguard.peer.config", ".wireguard.peer.key",
    ".wireguard.peer.priv", ".wireguard.peer.pub", ".wireguard.peer.private",
    ".wireguard.peer.public", ".wireguard.peer.psk", ".wireguard.peer.preshared",
    ".wireguard.endpoint", ".wireguard.endpoint.conf", ".wireguard.endpoint.config",
    ".wireguard.endpoint.key", ".wireguard.endpoint.priv", ".wireguard.endpoint.pub",
    ".ipsec.key", ".ipsec.crt", ".ipsec.pem", ".ipsec.der", ".ipsec.p12", ".ipsec.pfx",
    ".ipsec.jks", ".ipsec.bks", ".ipsec.keystore", ".ipsec.truststore", ".ipsec.secrets",
    ".ipsec.secrets.key", ".ipsec.secrets.pem", ".ipsec.secrets.der", ".ipsec.secrets.p12",
    ".ipsec.secrets.pfx", ".ipsec.secrets.jks", ".ipsec.secrets.bks", ".ipsec.secrets.keystore",
    ".ipsec.secrets.truststore", ".ipsec.conf", ".ipsec.config", ".ipsec.psk",
    ".ipsec.preshared", ".ipsec.preshared.key", ".ipsec.preshared.psk",
    ".ipsec.preshared.secret", ".ipsec.preshared.secure", ".ipsec.preshared.enc",
    ".ipsec.preshared.encrypted", ".ipsec.preshared.crypt", ".ipsec.user",
    ".ipsec.user.psk", ".ipsec.user.preshared", ".ipsec.user.preshared.key",
    ".ipsec.user.preshared.psk", ".ipsec.user.preshared.secret", ".ipsec.user.preshared.secure",
    ".ipsec.user.preshared.enc", ".ipsec.user.preshared.encrypted", ".ipsec.user.preshared.crypt",
    ".strongswan.key", ".strongswan.crt", ".strongswan.pem", ".strongswan.der",
    ".strongswan.p12", ".strongswan.pfx", ".strongswan.jks", ".strongswan.bks",
    ".strongswan.keystore", ".strongswan.truststore", ".strongswan.conf",
    ".strongswan.config", ".strongswan.secrets", ".strongswan.secrets.key",
    ".strongswan.secrets.pem", ".strongswan.secrets.der", ".strongswan.secrets.p12",
    ".strongswan.secrets.pfx", ".strongswan.secrets.jks", ".strongswan.secrets.bks",
    ".strongswan.secrets.keystore", ".strongswan.secrets.truststore", ".swanctl.conf",
    ".swanctl.config", ".swanctl.key", ".swanctl.crt", ".swanctl.pem", ".swanctl.der",
    ".swanctl.p12", ".swanctl.pfx", ".swanctl.jks", ".swanctl.bks", ".swanctl.keystore",
    ".swanctl.truststore", ".swanctl.secrets", ".swanctl.secrets.key",
    ".swanctl.secrets.pem", ".swanctl.secrets.der", ".swanctl.secrets.p12",
    ".swanctl.secrets.pfx", ".swanctl.secrets.jks", ".swanctl.secrets.bks",
    ".swanctl.secrets.keystore", ".swanctl.secrets.truststore",
    ".asc", ".gpg", ".pgp", ".keyring", ".pubring", ".secring", ".gpg-key",
    ".pgp-key", ".gpg-pub", ".gpg-sec", ".pgp-pub", ".pgp-sec", ".gnupg",
    ".kbx", ".kbx-key", ".kbx-secret", ".gpg.conf", ".dirmngr.conf", ".gpg-agent.conf",
    ".pub.gpg", ".sec.gpg", ".trustdb.gpg", ".pubring.kbx", ".private-keys-v1.d",
    ".gpg2", ".gpg2.conf", ".gpg2-agent.conf", ".gpg2.d", ".gpg2.keyring",
    ".gpg2.pubring", ".gpg2.secring", ".gpg2.kbx", ".gpg2.kbx-key", ".gpg2.kbx-secret",
    ".gpg2.trustdb", ".gpg2.trustdb.gpg", ".gpg2.pubring.kbx", ".gpg2.private-keys-v1.d",
    ".gpg2.private-keys", ".gpg2.private-keys-v1", ".gpg2.private-keys-v1.d",
    ".gpg2.private-keys-v1.key", ".gpg2.private-keys-v1.key.enc",
    ".gpg2.private-keys-v1.key.crypt", ".gpg2.private-keys-v1.key.secure",
    ".gpg2.private-keys-v1.key.backup", ".gpg2.private-keys-v1.key.old",
    ".gpg2.private-keys-v1.key.default", ".gpg2.private-keys-v1.key.example",
    ".gpg2.private-keys-v1.key.sample", ".gpg2.private-keys-v1.key.template",
    ".gpg-agent", ".gpg-agent.ssh", ".gpg-agent.ssh-control", ".gpg-agent.ssh-sock",
    ".gpg-agent.sock", ".gpg-agent.extra", ".gpg-agent.extra.conf", ".gpg-agent.browser",
    ".gpg-agent.browser.conf", ".gpg-agent.pinentry", ".gpg-agent.pinentry.conf",
    ".gpg-agent.cache", ".gpg-agent.cache.conf", ".gpg-agent.log", ".gpg-agent.log.old",
    ".gpg-agent.log.1", ".gpg-agent.log.2", ".gpg-agent.log.3", ".gpg-agent.log.4",
    ".gpg-agent.log.5", ".gpg-agent.log.6", ".gpg-agent.log.7", ".gpg-agent.log.8",
    ".gpg-agent.log.9", ".gpg-agent.log.10", ".dirmngr", ".dirmngr.conf", ".dirmngr.cache",
    ".dirmngr.cache.conf", ".dirmngr.log", ".dirmngr.log.old", ".dirmngr.log.1",
    ".dirmngr.log.2", ".dirmngr.log.3", ".dirmngr.log.4", ".dirmngr.log.5",
    ".dirmngr.log.6", ".dirmngr.log.7", ".dirmngr.log.8", ".dirmngr.log.9",
    ".dirmngr.log.10", ".gnupg", ".gnupg.conf", ".gnupg.config", ".gnupg.default",
    ".gnupg.example", ".gnupg.sample", ".gnupg.template", ".gnupg.backup",
    ".gnupg.old", ".gnupg.save", ".gnupg.enc", ".gnupg.encrypted", ".gnupg.crypt",
    ".gnupg.secure", ".gnupg.keyring", ".gnupg.pubring", ".gnupg.secring",
    ".gnupg.kbx", ".gnupg.kbx-key", ".gnupg.kbx-secret", ".gnupg.trustdb",
    ".gnupg.trustdb.gpg", ".gnupg.pubring.kbx", ".gnupg.private-keys-v1.d",
    ".gnupg.private-keys", ".gnupg.private-keys-v1", ".gnupg.private-keys-v1.d",
    ".gnupg.private-keys-v1.key", ".gnupg.private-keys-v1.key.enc",
    ".gnupg.private-keys-v1.key.crypt", ".gnupg.private-keys-v1.key.secure",
    ".gnupg.private-keys-v1.key.backup", ".gnupg.private-keys-v1.key.old",
    ".gnupg.private-keys-v1.key.default", ".gnupg.private-keys-v1.key.example",
    ".gnupg.private-keys-v1.key.sample", ".gnupg.private-keys-v1.key.template",
    ".pgp2", ".pgp2.key", ".pgp2.key.enc", ".pgp2.key.crypt", ".pgp2.key.secure",
    ".pgp2.key.backup", ".pgp2.key.old", ".pgp2.key.default", ".pgp2.key.example",
    ".pgp2.key.sample", ".pgp2.key.template", ".pgp2.pub", ".pgp2.pub.enc",
    ".pgp2.pub.crypt", ".pgp2.pub.secure", ".pgp2.pub.backup", ".pgp2.pub.old",
    ".pgp2.pub.default", ".pgp2.pub.example", ".pgp2.pub.sample", ".pgp2.pub.template",
    ".pgp2.sec", ".pgp2.sec.enc", ".pgp2.sec.crypt", ".pgp2.sec.secure",
    ".pgp2.sec.backup", ".pgp2.sec.old", ".pgp2.sec.default", ".pgp2.sec.example",
    ".pgp2.sec.sample", ".pgp2.sec.template", ".pgp2.keyring", ".pgp2.pubring",
    ".pgp2.secring", ".pgp2.kbx", ".pgp2.kbx-key", ".pgp2.kbx-secret", ".pgp2.trustdb",
    ".pgp2.trustdb.gpg", ".pgp2.pubring.kbx", ".pgp2.private-keys-v1.d",
    ".pgp6", ".pgp6.key", ".pgp6.key.enc", ".pgp6.key.crypt", ".pgp6.key.secure",
    ".pgp6.key.backup", ".pgp6.key.old", ".pgp6.key.default", ".pgp6.key.example",
    ".pgp6.key.sample", ".pgp6.key.template", ".pgp6.pub", ".pgp6.pub.enc",
    ".pgp6.pub.crypt", ".pgp6.pub.secure", ".pgp6.pub.backup", ".pgp6.pub.old",
    ".pgp6.pub.default", ".pgp6.pub.example", ".pgp6.pub.sample", ".pgp6.pub.template",
    ".pgp6.sec", ".pgp6.sec.enc", ".pgp6.sec.crypt", ".pgp6.sec.secure",
    ".pgp6.sec.backup", ".pgp6.sec.old", ".pgp6.sec.default", ".pgp6.sec.example",
    ".pgp6.sec.sample", ".pgp6.sec.template", ".pgp6.keyring", ".pgp6.pubring",
    ".pgp6.secring", ".pgp6.kbx", ".pgp6.kbx-key", ".pgp6.kbx-secret", ".pgp6.trustdb",
    ".pgp6.trustdb.gpg", ".pgp6.pubring.kbx", ".pgp6.private-keys-v1.d",
    ".ec", ".ecdsa", ".dsa", ".rsa", ".ed25519", ".ed448", ".xmss", ".sphincs",
    ".bls", ".bls12381", ".bn256", ".curve25519", ".curve448", ".p256", ".p384",
    ".p521", ".secp256k1", ".secp256r1", ".secp384r1", ".secp521r1", ".prime256v1",
    ".brainpoolP256r1", ".brainpoolP384r1", ".brainpoolP512r1", ".x25519", ".x448",
    ".pkcs1", ".pkcs8", ".openssl", ".ssl", ".ca", ".cabundle",
    ".rsa2", ".rsa3", ".rsa4", ".rsa5", ".rsa6", ".rsa7", ".rsa8", ".rsa9",
    ".rsa10", ".rsa2048", ".rsa3072", ".rsa4096", ".rsa8192", ".rsa16384",
    ".rsa.key", ".rsa.key.enc", ".rsa.key.crypt", ".rsa.key.secure", ".rsa.key.backup",
    ".rsa.key.old", ".rsa.key.default", ".rsa.key.example", ".rsa.key.sample",
    ".rsa.key.template", ".rsa.pub", ".rsa.pub.enc", ".rsa.pub.crypt", ".rsa.pub.secure",
    ".rsa.pub.backup", ".rsa.pub.old", ".rsa.pub.default", ".rsa.pub.example",
    ".rsa.pub.sample", ".rsa.pub.template", ".rsa.priv", ".rsa.priv.enc",
    ".rsa.priv.crypt", ".rsa.priv.secure", ".rsa.priv.backup", ".rsa.priv.old",
    ".rsa.priv.default", ".rsa.priv.example", ".rsa.priv.sample", ".rsa.priv.template",
    ".dsa2", ".dsa3", ".dsa4", ".dsa5", ".dsa6", ".dsa7", ".dsa8", ".dsa9",
    ".dsa10", ".dsa1024", ".dsa2048", ".dsa3072", ".dsa4096", ".dsa.key",
    ".dsa.key.enc", ".dsa.key.crypt", ".dsa.key.secure", ".dsa.key.backup",
    ".dsa.key.old", ".dsa.key.default", ".dsa.key.example", ".dsa.key.sample",
    ".dsa.key.template", ".dsa.pub", ".dsa.pub.enc", ".dsa.pub.crypt",
    ".dsa.pub.secure", ".dsa.pub.backup", ".dsa.pub.old", ".dsa.pub.default",
    ".dsa.pub.example", ".dsa.pub.sample", ".dsa.pub.template", ".dsa.priv",
    ".dsa.priv.enc", ".dsa.priv.crypt", ".dsa.priv.secure", ".dsa.priv.backup",
    ".dsa.priv.old", ".dsa.priv.default", ".dsa.priv.example", ".dsa.priv.sample",
    ".dsa.priv.template", ".ec2", ".ec3", ".ec4", ".ec5", ".ec6", ".ec7", ".ec8",
    ".ec9", ".ec10", ".ec192", ".ec224", ".ec256", ".ec384", ".ec521", ".ec.key",
    ".ec.key.enc", ".ec.key.crypt", ".ec.key.secure", ".ec.key.backup", ".ec.key.old",
    ".ec.key.default", ".ec.key.example", ".ec.key.sample", ".ec.key.template",
    ".ec.pub", ".ec.pub.enc", ".ec.pub.crypt", ".ec.pub.secure", ".ec.pub.backup",
    ".ec.pub.old", ".ec.pub.default", ".ec.pub.example", ".ec.pub.sample",
    ".ec.pub.template", ".ec.priv", ".ec.priv.enc", ".ec.priv.crypt", ".ec.priv.secure",
    ".ec.priv.backup", ".ec.priv.old", ".ec.priv.default", ".ec.priv.example",
    ".ec.priv.sample", ".ec.priv.template", ".ecdsa2", ".ecdsa3", ".ecdsa4",
    ".ecdsa5", ".ecdsa6", ".ecdsa7", ".ecdsa8", ".ecdsa9", ".ecdsa10", ".ecdsa192",
    ".ecdsa224", ".ecdsa256", ".ecdsa384", ".ecdsa521", ".ecdsa.key", ".ecdsa.key.enc",
    ".ecdsa.key.crypt", ".ecdsa.key.secure", ".ecdsa.key.backup", ".ecdsa.key.old",
    ".ecdsa.key.default", ".ecdsa.key.example", ".ecdsa.key.sample", ".ecdsa.key.template",
    ".ecdsa.pub", ".ecdsa.pub.enc", ".ecdsa.pub.crypt", ".ecdsa.pub.secure",
    ".ecdsa.pub.backup", ".ecdsa.pub.old", ".ecdsa.pub.default", ".ecdsa.pub.example",
    ".ecdsa.pub.sample", ".ecdsa.pub.template", ".ecdsa.priv", ".ecdsa.priv.enc",
    ".ecdsa.priv.crypt", ".ecdsa.priv.secure", ".ecdsa.priv.backup", ".ecdsa.priv.old",
    ".ecdsa.priv.default", ".ecdsa.priv.example", ".ecdsa.priv.sample",
    ".ecdsa.priv.template", ".ed25519.key", ".ed25519.key.enc", ".ed25519.key.crypt",
    ".ed25519.key.secure", ".ed25519.key.backup", ".ed25519.key.old",
    ".ed25519.key.default", ".ed25519.key.example", ".ed25519.key.sample",
    ".ed25519.key.template", ".ed25519.pub", ".ed25519.pub.enc", ".ed25519.pub.crypt",
    ".ed25519.pub.secure", ".ed25519.pub.backup", ".ed25519.pub.old",
    ".ed25519.pub.default", ".ed25519.pub.example", ".ed25519.pub.sample",
    ".ed25519.pub.template", ".ed25519.priv", ".ed25519.priv.enc", ".ed25519.priv.crypt",
    ".ed25519.priv.secure", ".ed25519.priv.backup", ".ed25519.priv.old",
    ".ed25519.priv.default", ".ed25519.priv.example", ".ed25519.priv.sample",
    ".ed25519.priv.template", ".ed448.key", ".ed448.key.enc", ".ed448.key.crypt",
    ".ed448.key.secure", ".ed448.key.backup", ".ed448.key.old", ".ed448.key.default",
    ".ed448.key.example", ".ed448.key.sample", ".ed448.key.template", ".ed448.pub",
    ".ed448.pub.enc", ".ed448.pub.crypt", ".ed448.pub.secure", ".ed448.pub.backup",
    ".ed448.pub.old", ".ed448.pub.default", ".ed448.pub.example", ".ed448.pub.sample",
    ".ed448.pub.template", ".ed448.priv", ".ed448.priv.enc", ".ed448.priv.crypt",
    ".ed448.priv.secure", ".ed448.priv.backup", ".ed448.priv.old", ".ed448.priv.default",
    ".ed448.priv.example", ".ed448.priv.sample", ".ed448.priv.template",
    ".x25519.key", ".x25519.key.enc", ".x25519.key.crypt", ".x25519.key.secure",
    ".x25519.key.backup", ".x25519.key.old", ".x25519.key.default", ".x25519.key.example",
    ".x25519.key.sample", ".x25519.key.template", ".x25519.pub", ".x25519.pub.enc",
    ".x25519.pub.crypt", ".x25519.pub.secure", ".x25519.pub.backup", ".x25519.pub.old",
    ".x25519.pub.default", ".x25519.pub.example", ".x25519.pub.sample",
    ".x25519.pub.template", ".x25519.priv", ".x25519.priv.enc", ".x25519.priv.crypt",
    ".x25519.priv.secure", ".x25519.priv.backup", ".x25519.priv.old",
    ".x25519.priv.default", ".x25519.priv.example", ".x25519.priv.sample",
    ".x25519.priv.template", ".x448.key", ".x448.key.enc", ".x448.key.crypt",
    ".x448.key.secure", ".x448.key.backup", ".x448.key.old", ".x448.key.default",
    ".x448.key.example", ".x448.key.sample", ".x448.key.template", ".x448.pub",
    ".x448.pub.enc", ".x448.pub.crypt", ".x448.pub.secure", ".x448.pub.backup",
    ".x448.pub.old", ".x448.pub.default", ".x448.pub.example", ".x448.pub.sample",
    ".x448.pub.template", ".x448.priv", ".x448.priv.enc", ".x448.priv.crypt",
    ".x448.priv.secure", ".x448.priv.backup", ".x448.priv.old", ".x448.priv.default",
    ".x448.priv.example", ".x448.priv.sample", ".x448.priv.template",
    ".curve25519.key", ".curve25519.key.enc", ".curve25519.key.crypt",
    ".curve25519.key.secure", ".curve25519.key.backup", ".curve25519.key.old",
    ".curve25519.key.default", ".curve25519.key.example", ".curve25519.key.sample",
    ".curve25519.key.template", ".curve25519.pub", ".curve25519.pub.enc",
    ".curve25519.pub.crypt", ".curve25519.pub.secure", ".curve25519.pub.backup",
    ".curve25519.pub.old", ".curve25519.pub.default", ".curve25519.pub.example",
    ".curve25519.pub.sample", ".curve25519.pub.template", ".curve25519.priv",
    ".curve25519.priv.enc", ".curve25519.priv.crypt", ".curve25519.priv.secure",
    ".curve25519.priv.backup", ".curve25519.priv.old", ".curve25519.priv.default",
    ".curve25519.priv.example", ".curve25519.priv.sample", ".curve25519.priv.template",
    ".keytab", ".krb5", ".krb5.keytab", ".k5identity", ".k5login", ".k5users",
    ".kdc.conf", ".krb5.conf", ".kadm5.acl", ".kdc", ".kadmin", ".kpasswd",
    ".ccache", ".credentials-cache", ".tgt", ".service.keytab", ".host.keytab",
    ".user.keytab", ".krb5cc", ".krb5kt", ".krb5keytab",
    ".krb5.ini", ".krb5.ini.default", ".krb5.ini.example", ".krb5.ini.sample",
    ".krb5.ini.template", ".krb5.ini.backup", ".krb5.ini.old", ".krb5.ini.save",
    ".krb5.ini.enc", ".krb5.ini.encrypted", ".krb5.ini.crypt", ".krb5.ini.secure",
    ".krb5.conf.d", ".krb5.conf.d.default", ".krb5.conf.d.example", ".krb5.conf.d.sample",
    ".krb5.conf.d.template", ".krb5.conf.d.backup", ".krb5.conf.d.old", ".krb5.conf.d.save",
    ".krb5.conf.d.enc", ".krb5.conf.d.encrypted", ".krb5.conf.d.crypt", ".krb5.conf.d.secure",
    ".krb5.keytab.default", ".krb5.keytab.example", ".krb5.keytab.sample",
    ".krb5.keytab.template", ".krb5.keytab.backup", ".krb5.keytab.old", ".krb5.keytab.save",
    ".krb5.keytab.enc", ".krb5.keytab.encrypted", ".krb5.keytab.crypt", ".krb5.keytab.secure",
    ".krb5.keytab.new", ".krb5.keytab.old", ".krb5.keytab.bak", ".krb5.keytab.bak2",
    ".krb5.keytab.bak3", ".krb5.keytab.bak4", ".krb5.keytab.bak5", ".krb5.keytab.bak6",
    ".krb5.keytab.bak7", ".krb5.keytab.bak8", ".krb5.keytab.bak9", ".krb5.keytab.bak10",
    ".k5identity.default", ".k5identity.example", ".k5identity.sample", ".k5identity.template",
    ".k5identity.backup", ".k5identity.old", ".k5identity.save", ".k5identity.enc",
    ".k5identity.encrypted", ".k5identity.crypt", ".k5identity.secure", ".k5login.default",
    ".k5login.example", ".k5login.sample", ".k5login.template", ".k5login.backup",
    ".k5login.old", ".k5login.save", ".k5login.enc", ".k5login.encrypted", ".k5login.crypt",
    ".k5login.secure", ".k5users.default", ".k5users.example", ".k5users.sample",
    ".k5users.template", ".k5users.backup", ".k5users.old", ".k5users.save", ".k5users.enc",
    ".k5users.encrypted", ".k5users.crypt", ".k5users.secure", ".kdc.conf.default",
    ".kdc.conf.example", ".kdc.conf.sample", ".kdc.conf.template", ".kdc.conf.backup",
    ".kdc.conf.old", ".kdc.conf.save", ".kdc.conf.enc", ".kdc.conf.encrypted",
    ".kdc.conf.crypt", ".kdc.conf.secure", ".kadm5.acl.default", ".kadm5.acl.example",
    ".kadm5.acl.sample", ".kadm5.acl.template", ".kadm5.acl.backup", ".kadm5.acl.old",
    ".kadm5.acl.save", ".kadm5.acl.enc", ".kadm5.acl.encrypted", ".kadm5.acl.crypt",
    ".kadm5.acl.secure", ".kdc.default", ".kdc.example", ".kdc.sample", ".kdc.template",
    ".kdc.backup", ".kdc.old", ".kdc.save", ".kdc.enc", ".kdc.encrypted", ".kdc.crypt",
    ".kdc.secure", ".kadmin.default", ".kadmin.example", ".kadmin.sample", ".kadmin.template",
    ".kadmin.backup", ".kadmin.old", ".kadmin.save", ".kadmin.enc", ".kadmin.encrypted",
    ".kadmin.crypt", ".kadmin.secure", ".kpasswd.default", ".kpasswd.example",
    ".kpasswd.sample", ".kpasswd.template", ".kpasswd.backup", ".kpasswd.old",
    ".kpasswd.save", ".kpasswd.enc", ".kpasswd.encrypted", ".kpasswd.crypt",
    ".kpasswd.secure", ".ccache.default", ".ccache.example", ".ccache.sample",
    ".ccache.template", ".ccache.backup", ".ccache.old", ".ccache.save", ".ccache.enc",
    ".ccache.encrypted", ".ccache.crypt", ".ccache.secure", ".tgt.default", ".tgt.example",
    ".tgt.sample", ".tgt.template", ".tgt.backup", ".tgt.old", ".tgt.save", ".tgt.enc",
    ".tgt.encrypted", ".tgt.crypt", ".tgt.secure",
    ".jks", ".keystore", ".truststore", ".bks", ".ubr", ".ce", ".cacerts",
    ".jssecacerts", ".keystore.jks", ".truststore.jks", ".keystore.bks",
    ".truststore.bks", ".jceks", ".jck", ".p12-keystore", ".pfx-keystore",
    ".keychain", ".keychain-db", ".login.keychain", ".system.keychain",
    ".keyring", ".keyring-store", ".keyring-db",
    ".jks.default", ".jks.example", ".jks.sample", ".jks.template", ".jks.backup",
    ".jks.old", ".jks.save", ".jks.enc", ".jks.encrypted", ".jks.crypt", ".jks.secure",
    ".jks.new", ".jks.old", ".jks.bak", ".jks.bak2", ".jks.bak3", ".jks.bak4",
    ".jks.bak5", ".jks.bak6", ".jks.bak7", ".jks.bak8", ".jks.bak9", ".jks.bak10",
    ".keystore.default", ".keystore.example", ".keystore.sample", ".keystore.template",
    ".keystore.backup", ".keystore.old", ".keystore.save", ".keystore.enc",
    ".keystore.encrypted", ".keystore.crypt", ".keystore.secure", ".keystore.new",
    ".keystore.old", ".keystore.bak", ".keystore.bak2", ".keystore.bak3",
    ".keystore.bak4", ".keystore.bak5", ".keystore.bak6", ".keystore.bak7",
    ".keystore.bak8", ".keystore.bak9", ".keystore.bak10", ".truststore.default",
    ".truststore.example", ".truststore.sample", ".truststore.template",
    ".truststore.backup", ".truststore.old", ".truststore.save", ".truststore.enc",
    ".truststore.encrypted", ".truststore.crypt", ".truststore.secure",
    ".truststore.new", ".truststore.old", ".truststore.bak", ".truststore.bak2",
    ".truststore.bak3", ".truststore.bak4", ".truststore.bak5", ".truststore.bak6",
    ".truststore.bak7", ".truststore.bak8", ".truststore.bak9", ".truststore.bak10",
    ".bks.default", ".bks.example", ".bks.sample", ".bks.template", ".bks.backup",
    ".bks.old", ".bks.save", ".bks.enc", ".bks.encrypted", ".bks.crypt", ".bks.secure",
    ".bks.new", ".bks.old", ".bks.bak", ".bks.bak2", ".bks.bak3", ".bks.bak4",
    ".bks.bak5", ".bks.bak6", ".bks.bak7", ".bks.bak8", ".bks.bak9", ".bks.bak10",
    ".jceks.default", ".jceks.example", ".jceks.sample", ".jceks.template",
    ".jceks.backup", ".jceks.old", ".jceks.save", ".jceks.enc", ".jceks.encrypted",
    ".jceks.crypt", ".jceks.secure", ".jceks.new", ".jceks.old", ".jceks.bak",
    ".jceks.bak2", ".jceks.bak3", ".jceks.bak4", ".jceks.bak5", ".jceks.bak6",
    ".jceks.bak7", ".jceks.bak8", ".jceks.bak9", ".jceks.bak10", ".jck.default",
    ".jck.example", ".jck.sample", ".jck.template", ".jck.backup", ".jck.old",
    ".jck.save", ".jck.enc", ".jck.encrypted", ".jck.crypt", ".jck.secure",
    ".jck.new", ".jck.old", ".jck.bak", ".jck.bak2", ".jck.bak3", ".jck.bak4",
    ".jck.bak5", ".jck.bak6", ".jck.bak7", ".jck.bak8", ".jck.bak9", ".jck.bak10",
    ".cacerts.default", ".cacerts.example", ".cacerts.sample", ".cacerts.template",
    ".cacerts.backup", ".cacerts.old", ".cacerts.save", ".cacerts.enc", ".cacerts.encrypted",
    ".cacerts.crypt", ".cacerts.secure", ".cacerts.new", ".cacerts.old", ".cacerts.bak",
    ".cacerts.bak2", ".cacerts.bak3", ".cacerts.bak4", ".cacerts.bak5", ".cacerts.bak6",
    ".cacerts.bak7", ".cacerts.bak8", ".cacerts.bak9", ".cacerts.bak10",
    ".jssecacerts.default", ".jssecacerts.example", ".jssecacerts.sample",
    ".jssecacerts.template", ".jssecacerts.backup", ".jssecacerts.old",
    ".jssecacerts.save", ".jssecacerts.enc", ".jssecacerts.encrypted",
    ".jssecacerts.crypt", ".jssecacerts.secure", ".jssecacerts.new", ".jssecacerts.old",
    ".jssecacerts.bak", ".jssecacerts.bak2", ".jssecacerts.bak3", ".jssecacerts.bak4",
    ".jssecacerts.bak5", ".jssecacerts.bak6", ".jssecacerts.bak7", ".jssecacerts.bak8",
    ".jssecacerts.bak9", ".jssecacerts.bak10", ".keychain.default", ".keychain.example",
    ".keychain.sample", ".keychain.template", ".keychain.backup", ".keychain.old",
    ".keychain.save", ".keychain.enc", ".keychain.encrypted", ".keychain.crypt",
    ".keychain.secure", ".keychain.new", ".keychain.old", ".keychain.bak",
    ".keychain.bak2", ".keychain.bak3", ".keychain.bak4", ".keychain.bak5",
    ".keychain.bak6", ".keychain.bak7", ".keychain.bak8", ".keychain.bak9",
    ".keychain.bak10", ".keyring.default", ".keyring.example", ".keyring.sample",
    ".keyring.template", ".keyring.backup", ".keyring.old", ".keyring.save",
    ".keyring.enc", ".keyring.encrypted", ".keyring.crypt", ".keyring.secure",
    ".keyring.new", ".keyring.old", ".keyring.bak", ".keyring.bak2", ".keyring.bak3",
    ".keyring.bak4", ".keyring.bak5", ".keyring.bak6", ".keyring.bak7",
    ".keyring.bak8", ".keyring.bak9", ".keyring.bak10",
    ".kdb", ".kdbx", ".kdbx.enc", ".kdbx.encrypted", ".kdbx.crypt", ".kdbx.secure",
    ".kdbx.backup", ".kdbx.old", ".kdbx.save", ".kdbx.default", ".kdbx.example",
    ".kdbx.sample", ".kdbx.template", ".keepass", ".keepass.enc", ".keepass.encrypted",
    ".keepass.crypt", ".keepass.secure", ".keepass.backup", ".keepass.old",
    ".keepass.save", ".keepass.default", ".keepass.example", ".keepass.sample",
    ".keepass.template", ".keepass2", ".keepass2.enc", ".keepass2.encrypted",
    ".keepass2.crypt", ".keepass2.secure", ".keepass2.backup", ".keepass2.old",
    ".keepass2.save", ".keepass2.default", ".keepass2.example", ".keepass2.sample",
    ".keepass2.template", ".keepassx", ".keepassx.enc", ".keepassx.encrypted",
    ".keepassx.crypt", ".keepassx.secure", ".keepassx.backup", ".keepassx.old",
    ".keepassx.save", ".keepassx.default", ".keepassx.example", ".keepassx.sample",
    ".keepassx.template", ".1password", ".1password.enc", ".1password.encrypted",
    ".1password.crypt", ".1password.secure", ".1password.backup", ".1password.old",
    ".1password.save", ".1password.default", ".1password.example", ".1password.sample",
    ".1password.template", ".1pif", ".1pif.enc", ".1pif.encrypted", ".1pif.crypt",
    ".1pif.secure", ".1pif.backup", ".1pif.old", ".1pif.save", ".1pif.default",
    ".1pif.example", ".1pif.sample", ".1pif.template", ".agilekeychain",
    ".agilekeychain.enc", ".agilekeychain.encrypted", ".agilekeychain.crypt",
    ".agilekeychain.secure", ".agilekeychain.backup", ".agilekeychain.old",
    ".agilekeychain.save", ".agilekeychain.default", ".agilekeychain.example",
    ".agilekeychain.sample", ".agilekeychain.template", ".opvault", ".opvault.enc",
    ".opvault.encrypted", ".opvault.crypt", ".opvault.secure", ".opvault.backup",
    ".opvault.old", ".opvault.save", ".opvault.default", ".opvault.example",
    ".opvault.sample", ".opvault.template", ".dashlane", ".dashlane.enc",
    ".dashlane.encrypted", ".dashlane.crypt", ".dashlane.secure", ".dashlane.backup",
    ".dashlane.old", ".dashlane.save", ".dashlane.default", ".dashlane.example",
    ".dashlane.sample", ".dashlane.template", ".lastpass", ".lastpass.enc",
    ".lastpass.encrypted", ".lastpass.crypt", ".lastpass.secure", ".lastpass.backup",
    ".lastpass.old", ".lastpass.save", ".lastpass.default", ".lastpass.example",
    ".lastpass.sample", ".lastpass.template", ".bitwarden", ".bitwarden.enc",
    ".bitwarden.encrypted", ".bitwarden.crypt", ".bitwarden.secure",
    ".bitwarden.backup", ".bitwarden.old", ".bitwarden.save", ".bitwarden.default",
    ".bitwarden.example", ".bitwarden.sample", ".bitwarden.template", ".vault",
    ".vault.enc", ".vault.encrypted", ".vault.crypt", ".vault.secure", ".vault.backup",
    ".vault.old", ".vault.save", ".vault.default", ".vault.example", ".vault.sample",
    ".vault.template", ".vaultpass", ".vaultpass.enc", ".vaultpass.encrypted",
    ".vaultpass.crypt", ".vaultpass.secure", ".vaultpass.backup", ".vaultpass.old",
    ".vaultpass.save", ".vaultpass.default", ".vaultpass.example", ".vaultpass.sample",
    ".vaultpass.template",
    ".pem.bak", ".key.bak", ".crt.bak", ".cer.bak", ".der.bak", ".p12.bak",
    ".pfx.bak", ".p7b.bak", ".p7c.bak", ".p7r.bak", ".p7s.bak", ".p8.bak",
    ".pkcs7.bak", ".pkcs8.bak", ".pkcs12.bak", ".p10.bak", ".csr.bak",
    ".crl.bak", ".sst.bak", ".spc.bak", ".jks.bak", ".keystore.bak",
    ".truststore.bak", ".bks.bak", ".ubr.bak", ".ce.bak", ".crtx.bak",
    ".crt64.bak", ".crt32.bak", ".ovpn.bak", ".cacert.bak", ".ca-bundle.bak",
    ".ca-certificates.bak", ".certificate.bak", ".certificates.bak",
    ".chain.bak", ".fullchain.bak", ".privkey.bak", ".certkey.bak",
    ".combined.bak", ".bundle.bak", ".intermediate.bak", ".intermediate.crt.bak",
    ".root.bak", ".root.crt.bak", ".issuer.bak", ".pem-key.bak", ".pem-crt.bak",
    ".key-pem.bak", ".crt-pem.bak", ".ssl-cert.bak", ".ssl-key.bak",
    ".tls.bak", ".tls-cert.bak", ".tls-key.bak", ".x509.bak", ".x509-cert.bak",
    ".x509-key.bak",
    ".2020", ".2021", ".2022", ".2023", ".2024", ".2025", ".old", ".old1",
    ".old2", ".old3", ".old4", ".old5", ".old6", ".old7", ".old8", ".old9",
    ".old10", ".bak1", ".bak2", ".bak3", ".bak4", ".bak5", ".bak6", ".bak7",
    ".bak8", ".bak9", ".bak10", ".backup1", ".backup2", ".backup3", ".backup4",
    ".backup5", ".backup6", ".backup7", ".backup8", ".backup9", ".backup10",
    ".save1", ".save2", ".save3", ".save4", ".save5", ".save6", ".save7",
    ".save8", ".save9", ".save10", ".1", ".2", ".3", ".4", ".5", ".6", ".7",
    ".8", ".9", ".10", ".v1", ".v2", ".v3", ".v4", ".v5", ".v6", ".v7", ".v8",
    ".v9", ".v10", ".ver1", ".ver2", ".ver3", ".ver4", ".ver5", ".ver6",
    ".ver7", ".ver8", ".ver9", ".ver10",
    ".sensitive", ".sensitive.enc", ".sensitive.encrypted", ".sensitive.crypt",
    ".sensitive.secure", ".sensitive.backup", ".sensitive.old", ".sensitive.save",
    ".sensitive.default", ".sensitive.example", ".sensitive.sample",
    ".sensitive.template", ".confidential", ".confidential.enc",
    ".confidential.encrypted", ".confidential.crypt", ".confidential.secure",
    ".confidential.backup", ".confidential.old", ".confidential.save",
    ".confidential.default", ".confidential.example", ".confidential.sample",
    ".confidential.template", ".private-data", ".private-data.enc",
    ".private-data.encrypted", ".private-data.crypt", ".private-data.secure",
    ".private-data.backup", ".private-data.old", ".private-data.save",
    ".private-data.default", ".private-data.example", ".private-data.sample",
    ".private-data.template", ".secure-data", ".secure-data.enc",
    ".secure-data.encrypted", ".secure-data.crypt", ".secure-data.secure",
    ".secure-data.backup", ".secure-data.old", ".secure-data.save",
    ".secure-data.default", ".secure-data.example", ".secure-data.sample",
    ".secure-data.template", ".encrypted-data", ".encrypted-data.enc",
    ".encrypted-data.encrypted", ".encrypted-data.crypt", ".encrypted-data.secure",
    ".encrypted-data.backup", ".encrypted-data.old", ".encrypted-data.save",
    ".encrypted-data.default", ".encrypted-data.example", ".encrypted-data.sample",
    ".encrypted-data.template",
}
