git_extensions = {
    ".git",
    ".gitattributes", ".gitignore", ".gitmodules", ".gitconfig",
    ".gitconfig.local", ".gitconfig.worktree", ".gitconfig.user",
    ".gitconfig.system", ".gitconfig.example", ".gitconfig.sample",
    ".gitconfig.template", ".gitconfig.backup", ".gitconfig.old",
    ".gitconfig.save", ".gitconfig.enc", ".gitconfig.encrypted",
    ".gitconfig.crypt", ".gitconfig.secure", ".gitconfig.default",
    ".gitconfig.custom", ".gitconfig.global", ".gitconfig.work",
    ".gitconfig.personal", ".gitconfig.project", ".gitconfig.team",
    ".gitconfig.override", ".gitconfig.machine", ".gitconfig.host",
    ".gitconfig.os", ".gitconfig.windows", ".gitconfig.linux",
    ".gitconfig.macos", ".gitconfig.darwin", ".gitconfig.unix",
    ".gitconfig.bsd", ".gitconfig.solaris", ".gitconfig.aix",
    ".gitconfig.hpux", ".gitignore_global", ".gitignore.local",
    ".gitignore.user", ".gitignore.worktree", ".gitignore.project",
    ".gitignore.team", ".gitignore.personal", ".gitignore.work",
    ".gitignore.custom", ".gitignore.override", ".gitignore.global",
    ".gitignore.system", ".gitignore.example", ".gitignore.sample",
    ".gitignore.template", ".gitignore.backup", ".gitignore.old",
    ".gitignore.save", ".gitignore.enc", ".gitignore.encrypted",
    ".gitignore.crypt", ".gitignore.secure", ".gitignore.default",
    ".gitignore.patterns", ".gitignore.extra", ".gitignore.additional",
    ".gitignore.supplemental", ".gitignore.exclude", ".gitignore.include",
    ".gitignore.all", ".gitignore.full", ".gitignore.complete",
    ".gitignore.basic", ".gitignore.advanced", ".gitignore.minimal",
    ".gitignore.extended", ".gitignore.recommended", ".gitignore.standard",
    ".gitignore.optimal", ".gitattributes_global", ".gitattributes.local",
    ".gitattributes.user", ".gitattributes.project", ".gitattributes.team",
    ".gitattributes.custom", ".gitattributes.override", ".gitattributes.example",
    ".gitattributes.sample", ".gitattributes.template", ".gitattributes.backup",
    ".gitattributes.old", ".gitattributes.save", ".gitattributes.enc",
    ".gitattributes.encrypted", ".gitattributes.crypt", ".gitattributes.secure",
    ".gitattributes.default", ".gitattributes.binary", ".gitattributes.text",
    ".gitattributes.merge", ".gitattributes.diff", ".gitattributes.filter",
    ".gitattributes.lfs", ".gitattributes.linguist", ".gitattributes.eol",
    ".gitattributes.ident", ".gitattributes.export-ignore",
    ".gitattributes.export-subst", ".gitattributes.working-tree-encoding",
    ".gitattributes.macro", ".gitmodules_global", ".gitmodules.local",
    ".gitmodules.user", ".gitmodules.project", ".gitmodules.team",
    ".gitmodules.custom", ".gitmodules.override", ".gitmodules.example",
    ".gitmodules.sample", ".gitmodules.template", ".gitmodules.backup",
    ".gitmodules.old", ".gitmodules.save", ".gitmodules.enc",
    ".gitmodules.encrypted", ".gitmodules.crypt", ".gitmodules.secure",
    ".gitmodules.default", ".gitmodules.submodule", ".gitmodules.submodules",
    ".gitmodules.recursive", ".gitmodules.branch", ".gitmodules.url",
    ".gitmodules.path", ".gitmodules.update", ".gitmodules.ignore",
    ".gitmodules.shallow", ".gitmodules.active", ".gitmodules.deinit",
    ".patch", ".diff", ".patch.gz", ".patch.bz2", ".patch.xz", ".patch.zst",
    ".diff.gz", ".diff.bz2", ".diff.xz", ".diff.zst", ".patch.sig",
    ".diff.sig", ".patch.asc", ".diff.asc", ".patch.pgp", ".diff.pgp",
    ".patch.gpg", ".diff.gpg", ".patch.enc", ".diff.enc", ".patch.encrypted",
    ".diff.encrypted", ".patch.crypt", ".diff.crypt", ".patch.secure",
    ".diff.secure", ".patch.backup", ".diff.backup", ".patch.old", ".diff.old",
    ".patch.save", ".diff.save", ".patch.default", ".diff.default",
    ".patch.example", ".diff.example", ".patch.sample", ".diff.sample",
    ".patch.template", ".diff.template", ".patch.v1", ".diff.v1", ".patch.v2",
    ".diff.v2", ".patch.v3", ".diff.v3", ".patch.v4", ".diff.v4", ".patch.v5",
    ".diff.v5", ".bundle", ".gitbundle", ".git-bundle", ".bundle.gz",
    ".bundle.bz2", ".bundle.xz", ".bundle.zst", ".bundle.enc",
    ".bundle.encrypted", ".bundle.crypt", ".bundle.secure", ".bundle.backup",
    ".bundle.old", ".bundle.save", ".bundle.default", ".bundle.example",
    ".bundle.sample", ".bundle.template", ".gitarchive", ".git-archive",
    ".archive", ".archive.gz", ".archive.bz2", ".archive.xz", ".archive.zst",
    ".gitarchive.gz", ".gitarchive.bz2", ".gitarchive.xz", ".gitarchive.zst",
    ".git-pack", ".pack", ".idx", ".bitmap", ".midx", ".multi-pack-index",
    ".commit-graph", ".commit-graph-chain", ".shallow", ".gc.log", ".reflog",
    ".git-log", ".worktree", ".worktree.lock", ".worktree.config",
    ".worktree.default", ".worktree.example", ".worktree.sample",
    ".worktree.template", ".worktree.backup", ".worktree.old",
    ".worktree.save", ".worktree.enc", ".worktree.encrypted",
    ".worktree.crypt", ".worktree.secure", ".git-worktree", ".git-worktree.lock",
    ".git-worktree.config", ".exclude", ".gitignore-exclude",
    ".gitignore.exclude", ".gitignore.exclude.local", ".gitignore.exclude.global",
    ".gitignore.exclude.user", ".gitignore.exclude.project",
    ".gitignore.exclude.team", ".gitignore.exclude.custom",
    ".gitignore.exclude.override", ".gitignore.exclude.example",
    ".gitignore.exclude.sample", ".gitignore.exclude.template",
    ".gitignore.exclude.backup", ".gitignore.exclude.old",
    ".gitignore.exclude.save", ".gitignore.exclude.enc",
    ".gitignore.exclude.encrypted", ".gitignore.exclude.crypt",
    ".gitignore.exclude.secure", ".gitignore.exclude.default",
    ".index", ".index.lock", ".bisect", ".bisect.log", ".bisect.config",
    ".bisect.default", ".bisect.example", ".bisect.sample", ".bisect.template",
    ".bisect.backup", ".bisect.old", ".bisect.save", ".bisect.enc",
    ".bisect.encrypted", ".bisect.crypt", ".bisect.secure",
    ".gitattributes.lfs.*", 
    ".gitmodules.lfs",  
    ".gitmodules.lfs-config",  
    ".git-lfs",  
    ".git-lfs.config",  
    ".git-lfs.attributes",  
    ".git-lfs.objects",  
    ".git-lfs.locks",  
    ".git-crypt",  
    ".git-crypt.keys", 
    ".git-crypt.config",  
    ".git-secrets",  
    ".git-secrets.config",  
    ".git-secrets.patterns",  
    ".git-annex",  
    ".git-annex.config",  
    ".git-annex.objects", 
    ".git-annex.logs", 
    ".git-mergetool",  
    ".git-mergetool.config",  
    ".git-difftool",  
    ".git-difftool.config",  
    ".git-shell-commands",  
    ".git-shell-commands.help",  
    ".git-shell-commands.quit",  
    ".git-daemon",  
    ".git-daemon.config",  
    ".git-http-backend",  
    ".git-upload-pack",  
    ".git-receive-pack",  
    ".git-maintenance", 
    ".git-maintenance.config",  
    ".git-gc",  
    ".git-gc.config",  
    ".git-prune", 
    ".git-fsck",  
    ".git-repack",  
    ".git-sparse-checkout",  
    ".git-template", 
    ".git-example",  
    ".git-sample",  
    ".gitconfig-user",  
    ".gitconfig-work",  
    ".gitconfig-project", 
    ".gitconfig-team",
    ".gitconfig-machine",  
    ".git-temp",  
    ".git-tmp",  
    ".git-cache",  
    ".git-state",  
    ".git-data",  
    ".git-info",  
    ".git-meta",  
    ".git-extra", 
}
