pip_extensions = {
    ".whl", ".whl.bak", ".whl.old", ".whl.save", ".whl.enc", ".whl.encrypted", ".whl.crypt", ".whl.secure",
    ".egg", ".egg.bak", ".egg.old", ".egg.save", ".egg.enc", ".egg.encrypted", ".egg.crypt", ".egg.secure",
    ".tar.gz", ".tar.bz2", ".tar.xz", ".tar.zst", ".zip", ".tgz", ".tbz2", ".txz", ".tzst",
    "requirements.txt", "requirements.txt.bak", "requirements.txt.old", "requirements.txt.save",
    "requirements.txt.enc", "requirements.txt.encrypted", "requirements.txt.crypt", "requirements.txt.secure",
    "requirements-dev.txt", "requirements-dev.txt.bak", "requirements-dev.txt.old", "requirements-dev.txt.save",
    "requirements-prod.txt", "requirements-prod.txt.bak", "requirements-prod.txt.old", "requirements-prod.txt.save",
    "requirements-test.txt", "requirements-test.txt.bak", "requirements-test.txt.old", "requirements-test.txt.save",
    "requirements-local.txt", "requirements-local.txt.bak", "requirements-local.txt.old", "requirements-local.txt.save",
    "requirements-staging.txt", "requirements-staging.txt.bak", "requirements-staging.txt.old", "requirements-staging.txt.save",
    "requirements-production.txt", "requirements-production.txt.bak", "requirements-production.txt.old",
    "requirements-production.txt.save", "requirements-ci.txt", "requirements-ci.txt.bak", "requirements-ci.txt.old",
    "requirements-ci.txt.save", "requirements-docs.txt", "requirements-docs.txt.bak", "requirements-docs.txt.old",
    "requirements-docs.txt.save", "requirements-deploy.txt", "requirements-deploy.txt.bak", "requirements-deploy.txt.old",
    "requirements-deploy.txt.save", "requirements-aws.txt", "requirements-aws.txt.bak", "requirements-aws.txt.old",
    "requirements-aws.txt.save", "requirements-azure.txt", "requirements-azure.txt.bak", "requirements-azure.txt.old",
    "requirements-azure.txt.save", "requirements-gcp.txt", "requirements-gcp.txt.bak", "requirements-gcp.txt.old",
    "requirements-gcp.txt.save", "requirements-docker.txt", "requirements-docker.txt.bak", "requirements-docker.txt.old",
    "requirements-docker.txt.save", "requirements-kubernetes.txt", "requirements-kubernetes.txt.bak",
    "requirements-kubernetes.txt.old", "requirements-kubernetes.txt.save",
    "constraints.txt", "constraints.txt.bak", "constraints.txt.old", "constraints.txt.save",
    "constraints.txt.enc", "constraints.txt.encrypted", "constraints.txt.crypt", "constraints.txt.secure",
    "constraints-dev.txt", "constraints-dev.txt.bak", "constraints-dev.txt.old", "constraints-dev.txt.save",
    "constraints-prod.txt", "constraints-prod.txt.bak", "constraints-prod.txt.old", "constraints-prod.txt.save",
    "pip.conf", "pip.conf.bak", "pip.conf.old", "pip.conf.save", "pip.conf.enc", "pip.conf.encrypted",
    "pip.conf.crypt", "pip.conf.secure", "pip.ini", "pip.ini.bak", "pip.ini.old", "pip.ini.save",
    "pip.ini.enc", "pip.ini.encrypted", "pip.ini.crypt", "pip.ini.secure", ".pip", ".pip.bak", ".pip.old",
    ".pip.save",
    ".pip-cache", ".pip-cache.bak", ".pip-cache.old", ".pip-cache.save", "pip-cache", "pip-cache.bak",
    "pip-cache.old", "pip-cache.save", "pip_cache", "pip_cache.bak", "pip_cache.old", "pip_cache.save",
    "PKG-INFO", "PKG-INFO.bak", "PKG-INFO.old", "PKG-INFO.save", "PKG-INFO.enc", "PKG-INFO.encrypted",
    "PKG-INFO.crypt", "PKG-INFO.secure", "METADATA", "METADATA.bak", "METADATA.old", "METADATA.save",
    "METADATA.enc", "METADATA.encrypted", "METADATA.crypt", "METADATA.secure", "entry_points.txt",
    "entry_points.txt.bak", "entry_points.txt.old", "entry_points.txt.save", "top_level.txt",
    "top_level.txt.bak", "top_level.txt.old", "top_level.txt.save",
    "setup.py", "setup.py.bak", "setup.py.old", "setup.py.save", "setup.py.enc", "setup.py.encrypted",
    "setup.py.crypt", "setup.py.secure", "setup.cfg", "setup.cfg.bak", "setup.cfg.old", "setup.cfg.save",
    "setup.cfg.enc", "setup.cfg.encrypted", "setup.cfg.crypt", "setup.cfg.secure", "setup.py.old",
    "setup.py.orig", "setup.py.backup", "setup.py.bak2", "setup.py.bak3",
    "pyproject.toml", "pyproject.toml.bak", "pyproject.toml.old", "pyproject.toml.save",
    "pyproject.toml.enc", "pyproject.toml.encrypted", "pyproject.toml.crypt", "pyproject.toml.secure",
    "pyproject.toml.backup", "pyproject.toml.orig", "pyproject.toml.v1", "pyproject.toml.v2",
    "poetry.lock", "poetry.lock.bak", "poetry.lock.old", "poetry.lock.save", "poetry.lock.enc",
    "poetry.lock.encrypted", "poetry.lock.crypt", "poetry.lock.secure",
    "Pipfile", "Pipfile.bak", "Pipfile.old", "Pipfile.save", "Pipfile.enc", "Pipfile.encrypted",
    "Pipfile.crypt", "Pipfile.secure", "Pipfile.lock", "Pipfile.lock.bak", "Pipfile.lock.old",
    "Pipfile.lock.save", "Pipfile.lock.enc", "Pipfile.lock.encrypted", "Pipfile.lock.crypt",
    "Pipfile.lock.secure",
    "pyvenv.cfg", "pyvenv.cfg.bak", "pyvenv.cfg.old", "pyvenv.cfg.save", "pyvenv.cfg.enc",
    "pyvenv.cfg.encrypted", "pyvenv.cfg.crypt", "pyvenv.cfg.secure", "venv", ".venv", ".virtualenv",
    "virtualenv", "env", ".env", "python-env", ".python-env", "pyenv", ".pyenv",
    ".pyc", ".pyo", ".pyd", ".pyc.bak", ".pyc.old", ".pyc.save", ".pyd.bak", ".pyd.old", ".pyd.save",
    "dist", "dist.bak", "dist.old", "dist.save", "build", "build.bak", "build.old", "build.save",
    ".eggs", ".eggs.bak", ".eggs.old", ".eggs.save", "dist-info", "dist-info.bak", "dist-info.old",
    "dist-info.save", "egg-info", "egg-info.bak", "egg-info.old", "egg-info.save",
    ".pypirc", ".pypirc.bak", ".pypirc.old", ".pypirc.save", ".pypirc.enc", ".pypirc.encrypted",
    ".pypirc.crypt", ".pypirc.secure", "pypirc", "pypirc.bak", "pypirc.old", "pypirc.save",
    ".pypi-token", ".pypi-token.bak", ".pypi-token.old", ".pypi-token.save", ".pypi-token.enc",
    ".pypi-token.encrypted", ".pypi-token.crypt", ".pypi-token.secure", "pypi_token.txt",
    "pypi_token.txt.bak", "pypi_token.txt.old", "pypi_token.txt.save",
    ".python-key", ".python-key.bak", ".python-key.old", ".python-key.save", ".python-key.enc",
    ".python-key.encrypted", ".python-key.crypt", ".python-key.secure", "python_key.pem",
    "python_key.pem.bak", "python_key.pem.old", "python_key.pem.save", "python_private_key.pem",
    "python_public_key.pem", "python_cert.pem", "python_cert.crt",
    ".python-env", ".python-env.bak", ".python-env.old", ".python-env.save", ".python-env.enc",
    ".python-env.encrypted", ".python-env.crypt", ".python-env.secure", "python.env", "python.env.bak",
    "python.env.old", "python.env.save", "python.env.enc", "python.env.encrypted", "python.env.crypt",
    "python.env.secure", "pypi.env", "pypi.env.bak", "pypi.env.old", "pypi.env.save",
    "pip.log", "pip.log.bak", "pip.log.old", "pip.log.save", "pip.log.gz", "pip.log.bz2", "pip.log.xz",
    "pip.log.zst", "pip.log.zip", ".pip.log", ".pip.log.bak", ".pip.log.old", ".pip.log.save",
    "pip-install.log", "pip-install.log.bak", "pip-install.log.old", "pip-install.log.save",
    "pip-install.log.gz", "pip-install.log.bz2", "pip-install.log.xz", "pip-install.log.zst",
    "pip-install.log.zip", "pip-debug.log", "pip-debug.log.bak", "pip-debug.log.old", "pip-debug.log.save",
    "pip-download", "pip-download.bak", "pip-download.old", "pip-download.save", "pip-download-cache",
    "pip-download-cache.bak", "pip-download-cache.old", "pip-download-cache.save", ".pip-download",
    ".pip-download.bak", ".pip-download.old", ".pip-download.save",
    ".dist-info", ".egg-info", ".wheel", ".wheel.bak", ".wheel.old", ".wheel.save", "WHEEL",
    "WHEEL.bak", "WHEEL.old", "WHEEL.save", "RECORD", "RECORD.bak", "RECORD.old", "RECORD.save",
    "INSTALLER", "INSTALLER.bak", "INSTALLER.old", "INSTALLER.save", "REQUESTED", "REQUESTED.bak",
    "REQUESTED.old", "REQUESTED.save", "DEPENDENCIES", "DEPENDENCIES.bak", "DEPENDENCIES.old",
    "DEPENDENCIES.save",
    ".python-secrets", ".python-secrets.bak", ".python-secrets.old", ".python-secrets.save",
    ".python-secrets.enc", ".python-secrets.encrypted", ".python-secrets.crypt", ".python-secrets.secure",
    "python-secrets.json", "python-secrets.json.bak", "python-secrets.json.old", "python-secrets.json.save",
    "python-secrets.yml", "python-secrets.yml.bak", "python-secrets.yml.old", "python-secrets.yml.save",
    "python-secrets.yaml", "python-secrets.yaml.bak", "python-secrets.yaml.old", "python-secrets.yaml.save",
    "api_keys.py", "api_keys.py.bak", "api_keys.py.old", "api_keys.py.save", "api_keys.py.enc",
    "api_keys.py.encrypted", "api_keys.py.crypt", "api_keys.py.secure", "credentials.py",
    "credentials.py.bak", "credentials.py.old", "credentials.py.save", "config.py", "config.py.bak",
    "config.py.old", "config.py.save", "settings.py", "settings.py.bak", "settings.py.old", "settings.py.save",
    "secrets.py", "secrets.py.bak", "secrets.py.old", "secrets.py.save", "secret.py", "secret.py.bak",
    "secret.py.old", "secret.py.save", "private.py", "private.py.bak", "private.py.old", "private.py.save",
    "conf.py", "conf.py.bak", "conf.py.old", "conf.py.save",
    "keyring", "keyring.bak", "keyring.old", "keyring.save", ".keyring", ".keyring.bak", ".keyring.old",
    ".keyring.save", "python_keyring", "python_keyring.bak", "python_keyring.old", "python_keyring.save",
    "keyring.cfg", "keyring.cfg.bak", "keyring.cfg.old", "keyring.cfg.save",
    "Pipenv", "Pipenv.bak", "Pipenv.old", "Pipenv.save", "Pipenv.lock", "Pipenv.lock.bak",
    "Pipenv.lock.old", "Pipenv.lock.save", "pipenv.pipfile", "pipenv.pipfile.bak", "pipenv.pipfile.old",
    "pipenv.pipfile.save",
    ".pypi", ".pypi.bak", ".pypi.old", ".pypi.save", ".pypi-upload", ".pypi-upload.bak", ".pypi-upload.old",
    ".pypi-upload.save", "pypi-upload.key", "pypi-upload.key.bak", "pypi-upload.key.old", "pypi-upload.key.save",
    "pypi-upload.token", "pypi-upload.token.bak", "pypi-upload.token.old", "pypi-upload.token.save",
    "pytest.ini", "pytest.ini.bak", "pytest.ini.old", "pytest.ini.save", ".pytest", ".pytest.bak",
    ".pytest.old", ".pytest.save", "pytest-cache", "pytest-cache.bak", "pytest-cache.old", "pytest-cache.save",
    ".pytest_cache", ".pytest_cache.bak", ".pytest_cache.old", ".pytest_cache.save", "test_credentials.py",
    "test_credentials.py.bak", "test_credentials.py.old", "test_credentials.py.save", "test_keys.py",
    "test_keys.py.bak", "test_keys.py.old", "test_keys.py.save", "test_secrets.py", "test_secrets.py.bak",
    "test_secrets.py.old", "test_secrets.py.save",
    ".ipynb", ".ipynb.bak", ".ipynb.old", ".ipynb.save", ".ipynb.enc", ".ipynb.encrypted", ".ipynb.crypt",
    ".ipynb.secure", "notebook.ipynb", "notebook.ipynb.bak", "notebook.ipynb.old", "notebook.ipynb.save",
    "jupyter_notebook_config.py", "jupyter_notebook_config.py.bak", "jupyter_notebook_config.py.old",
    "jupyter_notebook_config.py.save",
    "tox.ini", "tox.ini.bak", "tox.ini.old", "tox.ini.save", ".tox", ".tox.bak", ".tox.old", ".tox.save",
    "tox.ini.enc", "tox.ini.encrypted", "tox.ini.crypt", "tox.ini.secure",
    ".pre-commit-config.yaml", ".pre-commit-config.yaml.bak", ".pre-commit-config.yaml.old",
    ".pre-commit-config.yaml.save", ".pre-commit-config.yml", ".pre-commit-config.yml.bak",
    ".pre-commit-config.yml.old", ".pre-commit-config.yml.save", "pre-commit", "pre-commit.bak",
    "pre-commit.old", "pre-commit.save",
    "python-publish.yml", "python-publish.yaml", "python-publish.yml.bak", "python-publish.yaml.bak",
    "python-publish.yml.old", "python-publish.yaml.old", "python-publish.yml.save", "python-publish.yaml.save",
    "pypi-publish.yml", "pypi-publish.yaml", "pypi-publish.yml.bak", "pypi-publish.yaml.bak",
    "Dockerfile.python", "Dockerfile.python.bak", "Dockerfile.python.old", "Dockerfile.python.save",
    "docker-python", "docker-python.bak", "docker-python.old", "docker-python.save", ".dockerignore-python",
    ".dockerignore-python.bak", ".dockerignore-python.old", ".dockerignore-python.save",
    "boto3-credentials", "boto3-credentials.bak", "boto3-credentials.old", "boto3-credentials.save",
    "aws-python-keys", "aws-python-keys.bak", "aws-python-keys.old", "aws-python-keys.save",
    "python-aws.ini", "python-aws.ini.bak", "python-aws.ini.old", "python-aws.ini.save",
    "python-db-creds", "python-db-creds.bak", "python-db-creds.old", "python-db-creds.save",
    "python-sql-creds", "python-sql-creds.bak", "python-sql-creds.old", "python-sql-creds.save",
    "alembic.ini", "alembic.ini.bak", "alembic.ini.old", "alembic.ini.save", "alembic", "alembic.bak",
    "alembic.old", "alembic.save",
    "sqlalchemy.ini", "sqlalchemy.ini.bak", "sqlalchemy.ini.old", "sqlalchemy.ini.save",
    "django-settings.py", "django-settings.py.bak", "django-settings.py.old", "django-settings.py.save",
    "local_settings.py", "local_settings.py.bak", "local_settings.py.old", "local_settings.py.save",
    "prod_settings.py", "prod_settings.py.bak", "prod_settings.py.old", "prod_settings.py.save",
    "dev_settings.py", "dev_settings.py.bak", "dev_settings.py.old", "dev_settings.py.save",
    "staging_settings.py", "staging_settings.py.bak", "staging_settings.py.old", "staging_settings.py.save",
    "flask-config.py", "flask-config.py.bak", "flask-config.py.old", "flask-config.py.save",
    "flask-secret-key", "flask-secret-key.bak", "flask-secret-key.old", "flask-secret-key.save",
    "flask-env", "flask-env.bak", "flask-env.old", "flask-env.save", ".flaskenv", ".flaskenv.bak",
    ".flaskenv.old", ".flaskenv.save",
    "fastapi-config.py", "fastapi-config.py.bak", "fastapi-config.py.old", "fastapi-config.py.save",
    "fastapi-secret", "fastapi-secret.bak", "fastapi-secret.old", "fastapi-secret.save",
    "management", "management.bak", "management.old", "management.save", "commands", "commands.bak",
    "commands.old", "commands.save",
    ".py.bak", ".py.old", ".py.save", ".py.enc", ".py.encrypted", ".py.crypt", ".py.secure", ".py~",
    ".py.backup", ".py.orig", ".py.tmp", ".py.temp", ".py.1", ".py.2", ".py.3", ".py.4", ".py.5",
    ".py.v1", ".py.v2", ".py.v3", ".py.v4", ".py.v5",
    ".tar.gz.asc", ".tar.gz.sig", ".tar.gz.gpg", ".tar.gz.pgp", ".whl.asc", ".whl.sig", ".whl.gpg",
    ".whl.pgp", ".egg.asc", ".egg.sig", ".egg.gpg", ".egg.pgp",
    ".whl.encrypted", ".whl.crypt", ".whl.secure", ".egg.encrypted", ".egg.crypt", ".egg.secure",
    ".tar.gz.encrypted", ".tar.gz.crypt", ".tar.gz.secure",
    "activate", "activate.bat", "activate.ps1", "activate.fish", "activate.csh", "activate_this.py",
    "deactivate", "deactivate.bat", "deactivate.ps1", "deactivate.fish", "deactivate.csh",
    "environment.yml", "environment.yaml", "environment.yml.bak", "environment.yaml.bak",
    "environment.yml.old", "environment.yaml.old", "environment.yml.save", "environment.yaml.save",
    "conda-env.yml", "conda-env.yaml", "conda-env.yml.bak", "conda-env.yaml.bak",
    "pip-upgrade.log", "pip-upgrade.log.bak", "pip-upgrade.log.old", "pip-upgrade.log.save",
    "pip-upgrade.txt", "pip-upgrade.txt.bak", "pip-upgrade.txt.old", "pip-upgrade.txt.save",
    "freeze.txt", "freeze.txt.bak", "freeze.txt.old", "freeze.txt.save", "pip-freeze.txt",
    "pip-freeze.txt.bak", "pip-freeze.txt.old", "pip-freeze.txt.save",
    "depgraph.txt", "depgraph.txt.bak", "depgraph.txt.old", "depgraph.txt.save",
    "dependencies.json", "dependencies.json.bak", "dependencies.json.old", "dependencies.json.save",
    "dependencies.txt", "dependencies.txt.bak", "dependencies.txt.old", "dependencies.txt.save",
    "wheelhouse", "wheelhouse.bak", "wheelhouse.old", "wheelhouse.save", ".wheelhouse", ".wheelhouse.bak",
    ".wheelhouse.old", ".wheelhouse.save",
    "build.log", "build.log.bak", "build.log.old", "build.log.save", "build.txt", "build.txt.bak",
    "build.txt.old", "build.txt.save", "install.log", "install.log.bak", "install.log.old", "install.log.save",
    "compile.log", "compile.log.bak", "compile.log.old", "compile.log.save",
    "site-packages", "site-packages.bak", "site-packages.old", "site-packages.save", ".site-packages",
    ".site-packages.bak", ".site-packages.old", ".site-packages.save", "easy-install.pth",
    "easy-install.pth.bak", "easy-install.pth.old", "easy-install.pth.save",
    "namespace_packages.txt", "namespace_packages.txt.bak", "namespace_packages.txt.old",
    "namespace_packages.txt.save",
    "entry_points.txt.bak", "entry_points.txt.old", "entry_points.txt.save",
    ".egg-link", ".egg-link.bak", ".egg-link.old", ".egg-link.save",
    "installed-files.txt", "installed-files.txt.bak", "installed-files.txt.old", "installed-files.txt.save",
    "MANIFEST.in", "MANIFEST.in.bak", "MANIFEST.in.old", "MANIFEST.in.save",
    "README.pypi", "README.pypi.bak", "README.pypi.old", "README.pypi.save",
    "README.python", "README.python.bak", "README.python.old", "README.python.save",
}
