sql_extensions = {
    ".sql", ".sqlite", ".sqlite3", ".sqlite-wal", ".sqlite-shm", ".sqlite-journal",
    ".db", ".db3", ".db2", ".ddl", ".dml", ".sql.gz", ".sql.bz2", ".sql.xz", ".sql.zip",
    ".sql.7z", ".sql.enc", ".sql.encrypted", ".sql.crypt", ".sql.secure", ".sql.backup",
    ".sql.old", ".sql.save", ".sql.tmp", ".sql.temp", ".sql.bak", ".sql.bak2", ".sql.bak3",
    ".dump", ".dmp", ".dump.gz", ".dump.bz2", ".dump.xz", ".dump.zst", ".dump.zip",
    ".dmp.gz", ".dmp.bz2", ".dmp.xz", ".dmp.zst", ".dmp.zip", ".sql-dump", ".sql-dump.gz",
    ".db-dump", ".db-dump.gz", ".database-dump", ".database-dump.gz", ".backup.sql",
    ".backup.db", ".backup.dump", ".backup.dmp", ".dump.sql", ".dump.db", ".export.sql",
    ".export.db", ".export.dump",
    ".sqlbak", ".sqlbackup", ".dbbackup", ".dbak", ".databasebackup", ".db-bak", ".sql-bak",
    ".sqldump-backup", ".backup-sql", ".backup-db", ".backup-database", ".db-backup",
    ".sql-backup", ".database-backup", ".bk", ".bk2", ".bk3", ".bk4", ".bk5", ".bk6", ".bk7",
    ".bk8", ".bk9", ".bk10", ".bkp", ".bkp2", ".bkp3", ".bkp4", ".bkp5", ".bkp6", ".bkp7",
    ".bkp8", ".bkp9", ".bkp10",
    ".sqlite.db", ".sqlitedb", ".sqlite3.db", ".db.sqlite", ".db.sqlite3", ".sdb", ".sdb3",
    ".sl3", ".sl3.db", ".sqlite3-wal", ".sqlite3-shm", ".sqlite3-journal", ".sqlite3-backup",
    ".sqlite-backup", ".sqlite-bak", ".sqlite3-bak", ".sqlite-tmp", ".sqlite3-tmp",
    ".mdf", ".ldf", ".ndf", ".mdf.gz", ".ldf.gz", ".ndf.gz", ".mdf.bak", ".ldf.bak", ".ndf.bak",
    ".mdf.backup", ".ldf.backup", ".ndf.backup", ".mdf.old", ".ldf.old", ".ndf.old",
    ".mdf.save", ".ldf.save", ".ndf.save", ".mdf.enc", ".ldf.enc", ".ndf.enc",
    ".mdf.encrypted", ".ldf.encrypted", ".ndf.encrypted", ".mdf.crypt", ".ldf.crypt", ".ndf.crypt",
    ".mdf.secure", ".ldf.secure", ".ndf.secure", ".mdf.tmp", ".ldf.tmp", ".ndf.tmp",
    ".mdf.temp", ".ldf.temp", ".ndf.temp", ".mdf.dump", ".ldf.dump", ".ndf.dump",
    ".dbf", ".dbf.gz", ".dbf.bak", ".dbf.backup", ".dbf.old", ".dbf.save", ".dbf.enc",
    ".dbf.encrypted", ".dbf.crypt", ".dbf.secure", ".ora", ".ora.gz", ".ora.bak", ".ora.backup",
    ".ora.old", ".ora.save", ".ora.enc", ".ora.encrypted", ".ora.crypt", ".ora.secure",
    ".oradb", ".oradb.gz", ".oradb.bak", ".oradb.backup", ".oradb.old", ".oradb.save",
    ".oradb.enc", ".oradb.encrypted", ".oradb.crypt", ".oradb.secure", ".oracle-dump",
    ".oracle-dump.gz", ".oracle-backup", ".oracle-backup.gz", ".oracle-bak", ".oracle-bak.gz",
    ".sql.dump", ".sql.dmp", ".db.dump", ".db.dmp", ".database.dump", ".database.dmp",
    ".schema.sql", ".schema.dump", ".schema.db", ".data.sql", ".data.dump", ".data.db",
    ".structure.sql", ".structure.dump", ".structure.db", ".tables.sql", ".tables.dump",
    ".tables.db", ".views.sql", ".views.dump", ".views.db", ".procedures.sql", ".procedures.dump",
    ".functions.sql", ".functions.dump", ".triggers.sql", ".triggers.dump", ".indexes.sql",
    ".indexes.dump", ".constraints.sql", ".constraints.dump",
    ".sql.tar", ".sql.tar.gz", ".sql.tar.bz2", ".sql.tar.xz", ".sql.tar.zst", ".sql.tgz",
    ".sql.tbz2", ".sql.txz", ".sql.tzst", ".sql.7z", ".sql.rar", ".sql.gz.enc",
    ".sql.bz2.enc", ".sql.xz.enc", ".sql.zip.enc", ".sql.7z.enc", ".sql.rar.enc",
    ".sql.gz.encrypted", ".sql.bz2.encrypted", ".sql.xz.encrypted", ".sql.zip.encrypted",
    ".sql.7z.encrypted", ".sql.rar.encrypted", ".sql.gz.crypt", ".sql.bz2.crypt", ".sql.xz.crypt",
    ".sql.zip.crypt", ".sql.7z.crypt", ".sql.rar.crypt", ".sql.gz.secure", ".sql.bz2.secure",
    ".sql.xz.secure", ".sql.zip.secure", ".sql.7z.secure", ".sql.rar.secure",
    ".dbconf", ".dbconfig", ".database.conf", ".database.config", ".db-connection", ".db-conn",
    ".db-creds", ".db-credentials", ".db-passwords", ".db-pass", ".db-secrets", ".db-secret",
    ".db-keys", ".db-key", ".db-tokens", ".db-token", ".db-auth", ".db-authentication",
    ".database-creds", ".database-credentials", ".database-passwords", ".database-pass",
    ".database-secrets", ".database-secret", ".database-keys", ".database-key", ".database-tokens",
    ".database-token", ".database-auth", ".database-authentication", ".connection-string",
    ".connectionstrings", ".connstring", ".connstrings", ".dbstring", ".dbstrings",
    ".odbc", ".odbc.ini", ".odbc.conf", ".odbc.config", ".odbc.backup", ".odbc.old",
    ".odbc.save", ".odbc.enc", ".odbc.encrypted", ".odbc.crypt", ".odbc.secure",
    ".jdbc", ".jdbc.properties", ".jdbc.conf", ".jdbc.config", ".jdbc.backup", ".jdbc.old",
    ".jdbc.save", ".jdbc.enc", ".jdbc.encrypted", ".jdbc.crypt", ".jdbc.secure",
    ".dsn", ".dsn.conf", ".dsn.config", ".dsn.backup", ".dsn.old", ".dsn.save", ".dsn.enc",
    ".dsn.encrypted", ".dsn.crypt", ".dsn.secure", ".udl", ".udl.conf", ".udl.config",
    ".udl.backup", ".udl.old", ".udl.save", ".udl.enc", ".udl.encrypted", ".udl.crypt", ".udl.secure",
    ".dat", ".data", ".dbdata", ".database-data", ".sql-data", ".sqldata", ".db-data",
    ".database.db", ".db-database", ".sqldb", ".sqlitedb", ".db2.db", ".db2-data", ".db2-dump",
    ".oracle-data", ".oracle-db", ".ora-data", ".ora-db", ".sqlserver-data", ".sqlserver-db",
    ".mssql-data", ".mssql-db", ".sybase-data", ".sybase-db", ".informix-data", ".informix-db",
    ".firebird-data", ".firebird-db", ".interbase-data", ".interbase-db", ".dbase-data",
    ".dbase-db", ".foxpro-data", ".foxpro-db", ".paradox-data", ".paradox-db", ".access-data",
    ".access-db", ".mdb", ".accdb", ".mdb.bak", ".accdb.bak", ".mdb.backup", ".accdb.backup",
    ".mdb.old", ".accdb.old", ".mdb.save", ".accdb.save", ".mdb.enc", ".accdb.enc",
    ".mdb.encrypted", ".accdb.encrypted", ".mdb.crypt", ".accdb.crypt", ".mdb.secure", ".accdb.secure",
    ".query", ".queries", ".qry", ".qry.bak", ".qry.backup", ".qry.old", ".qry.save",
    ".qry.enc", ".qry.encrypted", ".qry.crypt", ".qry.secure", ".sql-query", ".sql-queries",
    ".sql-qry", ".sql-qrys", ".db-query", ".db-queries", ".db-qry", ".db-qrys",
    ".select.sql", ".insert.sql", ".update.sql", ".delete.sql", ".create.sql", ".alter.sql",
    ".drop.sql", ".truncate.sql", ".merge.sql", ".upsert.sql", ".replace.sql",
    ".trn", ".trn.gz", ".trn.bak", ".trn.backup", ".trn.old", ".trn.save", ".trn.enc",
    ".trn.encrypted", ".trn.crypt", ".trn.secure", ".log", ".log.gz", ".log.bak", ".log.backup",
    ".log.old", ".log.save", ".log.enc", ".log.encrypted", ".log.crypt", ".log.secure",
    ".sqllog", ".sqllog.gz", ".sqllog.bak", ".sqllog.backup", ".sqllog.old", ".sqllog.save",
    ".sqllog.enc", ".sqllog.encrypted", ".sqllog.crypt", ".sqllog.secure", ".dblog", ".dblog.gz",
    ".dblog.bak", ".dblog.backup", ".dblog.old", ".dblog.save", ".dblog.enc", ".dblog.encrypted",
    ".dblog.crypt", ".dblog.secure", ".transaction-log", ".transaction-log.gz", ".translog",
    ".translog.gz", ".db-transaction", ".db-transaction.gz", ".sql-transaction", ".sql-transaction.gz",
    ".tmp.sql", ".temp.sql", ".tmp.db", ".temp.db", ".sql.tmp", ".sql.temp", ".db.tmp", ".db.temp",
    ".sqlite-tmp", ".sqlite3-tmp", ".sqlite-temp", ".sqlite3-temp", ".sqltmp", ".sqltemp",
    ".dbtmp", ".dbtemp", ".database-tmp", ".database-temp", ".tmp-sql", ".temp-sql", ".tmp-db",
    ".temp-db", ".tmp-database", ".temp-database", ".sql-work", ".sql-working", ".sql-proc",
    ".sql-process", ".sql-import", ".sql-export", ".sql-import-tmp", ".sql-export-tmp",
    ".enc.sql", ".enc.db", ".enc.dump", ".encrypted.sql", ".encrypted.db", ".encrypted.dump",
    ".crypt.sql", ".crypt.db", ".crypt.dump", ".secure.sql", ".secure.db", ".secure.dump",
    ".aes.sql", ".aes.db", ".aes.dump", ".aes256.sql", ".aes256.db", ".aes256.dump",
    ".blowfish.sql", ".blowfish.db", ".blowfish.dump", ".twofish.sql", ".twofish.db", ".twofish.dump",
    ".3des.sql", ".3des.db", ".3des.dump", ".tripledes.sql", ".tripledes.db", ".tripledes.dump",
    ".pgp.sql", ".pgp.db", ".pgp.dump", ".gpg.sql", ".gpg.db", ".gpg.dump",
    ".sql.backup2", ".sql.backup3", ".sql.backup4", ".sql.backup5", ".sql.backup6", ".sql.backup7",
    ".sql.backup8", ".sql.backup9", ".sql.backup10", ".db.backup2", ".db.backup3", ".db.backup4",
    ".db.backup5", ".db.backup6", ".db.backup7", ".db.backup8", ".db.backup9", ".db.backup10",
    ".database.backup2", ".database.backup3", ".database.backup4", ".database.backup5",
    ".database.backup6", ".database.backup7", ".database.backup8", ".database.backup9",
    ".database.backup10", ".dump.backup2", ".dump.backup3", ".dump.backup4", ".dump.backup5",
    ".dump.backup6", ".dump.backup7", ".dump.backup8", ".dump.backup9", ".dump.backup10",
    ".sql.tar.enc", ".sql.tgz.enc", ".sql.tbz2.enc", ".sql.txz.enc", ".sql.tzst.enc",
    ".sql.zip.encrypted", ".sql.7z.encrypted", ".sql.rar.encrypted", ".sql.tar.gz.encrypted",
    ".sql.tar.bz2.encrypted", ".sql.tar.xz.encrypted", ".sql.tar.zst.encrypted",
    ".db.tar.enc", ".db.tgz.enc", ".db.tbz2.enc", ".db.txz.enc", ".db.tzst.enc",
    ".db.zip.encrypted", ".db.7z.encrypted", ".db.rar.encrypted", ".db.tar.gz.encrypted",
    ".db.tar.bz2.encrypted", ".db.tar.xz.encrypted", ".db.tar.zst.encrypted",
    ".database.tar.enc", ".database.tgz.enc", ".database.tbz2.enc", ".database.txz.enc",
    ".database.tzst.enc", ".database.zip.encrypted", ".database.7z.encrypted",
    ".database.rar.encrypted", ".database.tar.gz.encrypted", ".database.tar.bz2.encrypted",
    ".database.tar.xz.encrypted", ".database.tar.zst.encrypted",
    ".sql.migrate", ".sql.migration", ".sql.migrations", ".db.migrate", ".db.migration",
    ".db.migrations", ".database.migrate", ".database.migration", ".database.migrations",
    ".sql.schema", ".sql.schemas", ".db.schema", ".db.schemas", ".database.schema",
    ".database.schemas", ".sql.seed", ".sql.seeds", ".db.seed", ".db.seeds", ".database.seed",
    ".database.seeds", ".sql.fixture", ".sql.fixtures", ".db.fixture", ".db.fixtures",
    ".database.fixture", ".database.fixtures",
    ".sqlconf", ".sqlconfig", ".dbconf", ".dbconfig", ".dbconf.yml", ".dbconf.yaml",
    ".sqlconf.yml", ".sqlconf.yaml", ".database.yml", ".database.yaml", ".database.json",
    ".db.yml", ".db.yaml", ".db.json", ".sql.yml", ".sql.yaml", ".sql.json",
    ".connection.yml", ".connection.yaml", ".connection.json", ".conn.yml", ".conn.yaml",
    ".conn.json", ".db-connection.yml", ".db-connection.yaml", ".db-connection.json",
    ".sqli", ".sql-injection", ".sql-injection-test", ".sqli-test", ".sqli-payload",
    ".sql-payload", ".sql-injection-payload", ".blind-sqli", ".time-based-sqli",
    ".error-based-sqli", ".union-based-sqli", ".boolean-based-sqli",
    ".metadata.sql", ".metadata.db", ".sql-metadata", ".db-metadata", ".database-metadata",
    ".catalog.sql", ".catalog.db", ".sql-catalog", ".db-catalog", ".database-catalog",
    ".dictionary.sql", ".dictionary.db", ".sql-dictionary", ".db-dictionary", ".database-dictionary",
    ".replication.sql", ".replication.db", ".sql-replication", ".db-replication", ".database-replication",
    ".partition.sql", ".partition.db", ".sql-partition", ".db-partition", ".database-partition",
    ".explain.sql", ".explain.db", ".sql-explain", ".db-explain", ".explain-plan.sql",
    ".explain-plan.db", ".execution-plan.sql", ".execution-plan.db", ".query-plan.sql",
    ".query-plan.db", ".query-analysis.sql", ".query-analysis.db", ".performance.sql",
    ".performance.db", ".sql-performance", ".db-performance", ".optimizer.sql", ".optimizer.db",
    ".sql-optimizer", ".db-optimizer", ".stats.sql", ".stats.db", ".sql-stats", ".db-stats",
    ".sql-statistics", ".db-statistics", ".database-statistics", ".query-stats.sql", ".query-stats.db",
    ".sp.sql", ".storedproc.sql", ".stored-procedure.sql", ".stored-procedures.sql",
    ".proc.sql", ".procedure.sql", ".procedures.sql", ".func.sql", ".function.sql",
    ".functions.sql", ".udf.sql", ".udf.db", ".sql-function", ".db-function",
    ".trigger.sql", ".triggers.sql", ".sql-trigger", ".db-trigger", ".view.sql",
    ".views.sql", ".sql-view", ".db-view", ".materialized-view.sql", ".materialized-views.sql",
    ".audit.sql", ".audit.db", ".sql-audit", ".db-audit", ".database-audit", ".audit-log.sql",
    ".audit-log.db", ".sql-audit-log", ".db-audit-log", ".security-audit.sql", ".security-audit.db",
    ".sql-security", ".db-security", ".compliance.sql", ".compliance.db", ".sql-compliance",
    ".db-compliance", ".gdpr.sql", ".gdpr.db", ".sql-gdpr", ".db-gdpr", ".hipaa.sql", ".hipaa.db",
    ".sql-hipaa", ".db-hipaa", ".pci.sql", ".pci.db", ".sql-pci", ".db-pci", ".pci-dss.sql",
    ".pci-dss.db", ".sql-pci-dss", ".db-pci-dss", ".sox.sql", ".sox.db", ".sql-sox", ".db-sox",
    ".sql.bak.enc", ".sql.bak.encrypted", ".sql.bak.crypt", ".sql.bak.secure",
    ".db.bak.enc", ".db.bak.encrypted", ".db.bak.crypt", ".db.bak.secure",
    ".dump.bak.enc", ".dump.bak.encrypted", ".dump.bak.crypt", ".dump.bak.secure",
    ".sql.backup.enc", ".sql.backup.encrypted", ".sql.backup.crypt", ".sql.backup.secure",
    ".db.backup.enc", ".db.backup.encrypted", ".db.backup.crypt", ".db.backup.secure",
    ".database.backup.enc", ".database.backup.encrypted", ".database.backup.crypt",
    ".database.backup.secure", ".dump.backup.enc", ".dump.backup.encrypted", ".dump.backup.crypt",
    ".dump.backup.secure",
    ".dw.sql", ".datawarehouse.sql", ".data-warehouse.sql", ".dw.db", ".datawarehouse.db",
    ".data-warehouse.db", ".dw-dump.sql", ".dw-dump.db", ".datawarehouse-dump.sql",
    ".datawarehouse-dump.db", ".etl.sql", ".etl.db", ".etl-dump.sql", ".etl-dump.db",
    ".etl-script.sql", ".etl-script.db", ".oltp.sql", ".oltp.db", ".olap.sql", ".olap.db",
    ".cube.sql", ".cube.db", ".data-cube.sql", ".data-cube.db", ".dimension.sql", ".dimension.db",
    ".dimensions.sql", ".dimensions.db", ".fact.sql", ".fact.db", ".facts.sql", ".facts.db",
    ".star-schema.sql", ".star-schema.db", ".snowflake-schema.sql", ".snowflake-schema.db",
    ".couchdb", ".couchdb.sql", ".couchdb.db", ".couchdb-dump", ".couchdb-dump.sql",
    ".couchdb-dump.db", ".couchdb-backup", ".couchdb-backup.sql", ".couchdb-backup.db",
    ".couchbase", ".couchbase.sql", ".couchbase.db", ".couchbase-dump", ".couchbase-dump.sql",
    ".couchbase-dump.db", ".couchbase-backup", ".couchbase-backup.sql", ".couchbase-backup.db",
    ".arangodb", ".arangodb.sql", ".arangodb.db", ".arangodb-dump", ".arangodb-dump.sql",
    ".arangodb-dump.db", ".arangodb-backup", ".arangodb-backup.sql", ".arangodb-backup.db",
    ".neo4j", ".neo4j.sql", ".neo4j.db", ".neo4j-dump", ".neo4j-dump.sql", ".neo4j-dump.db",
    ".neo4j-backup", ".neo4j-backup.sql", ".neo4j-backup.db", ".graphdb", ".graphdb.sql",
    ".graphdb.db", ".graphdb-dump", ".graphdb-dump.sql", ".graphdb-dump.db", ".graphdb-backup",
    ".graphdb-backup.sql", ".graphdb-backup.db",
    ".h2.db", ".h2.sql", ".h2-dump", ".h2-backup", ".h2.mv.db", ".h2.lock.db", ".h2.trace.db",
    ".hsqldb", ".hsql.db", ".hsql.sql", ".hsqldb-dump", ".hsqldb-backup", ".hsqldb.script",
    ".hsqldb.data", ".hsqldb.properties", ".derby.db", ".derby.sql", ".derby-dump", ".derby-backup",
    ".derby.log", ".derby.properties", ".derby-schema", ".sqlite-memory", ".sqlite3-memory",
    ".sqlite-inmemory", ".sqlite3-inmemory", ".memory.db", ".memory.sql", ".memdb", ".memdb.sql",
    ".inmemory.db", ".inmemory.sql", ".ram.db", ".ram.sql", ".tempdb", ".tempdb.sql", ".temp.db",
    ".sqlprof", ".sql-profile", ".dbprof", ".db-profile", ".database-prof", ".database-profile",
    ".sql-debug", ".sql-debugging", ".db-debug", ".db-debugging", ".sql-trace", ".db-trace",
    ".sql-tracing", ".db-tracing", ".sql-verbose", ".db-verbose", ".sqllog-debug", ".dblog-debug",
    ".sql-debug.log", ".db-debug.log", ".sql-profile.log", ".db-profile.log", ".sql-trace.log",
    ".db-trace.log", ".sqldebug", ".dbdebug", ".sqlprofile", ".dbprofile", ".sqltrace", ".dbtrace",
    ".monitor.sql", ".monitor.db", ".sql-monitor", ".db-monitor", ".sql-monitoring", ".db-monitoring",
    ".sql-watch", ".db-watch", ".sql-observe", ".db-observe", ".sql-telemetry", ".db-telemetry",
    ".sql-metrics", ".db-metrics", ".sql-stats.log", ".db-stats.log", ".sql-monitor.log", ".db-monitor.log",
    ".sql-performance.log", ".db-performance.log", ".sql-activity.log", ".db-activity.log",
    ".sql-events.log", ".db-events.log", ".sql-alerts.log", ".db-alerts.log",
    ".export.sql.gz", ".export.db.gz", ".export.dump.gz", ".export.sql.bz2", ".export.db.bz2",
    ".export.dump.bz2", ".export.sql.xz", ".export.db.xz", ".export.dump.xz", ".export.sql.zst",
    ".export.db.zst", ".export.dump.zst", ".export.sql.tar", ".export.db.tar", ".export.dump.tar",
    ".export.sql.zip", ".export.db.zip", ".export.dump.zip", ".sql-export.gz", ".db-export.gz",
    ".database-export.gz", ".sql-export.bz2", ".db-export.bz2", ".database-export.bz2",
    ".sql-export.xz", ".db-export.xz", ".database-export.xz", ".sql-export.zst", ".db-export.zst",
    ".database-export.zst", ".sql-export.tar", ".db-export.tar", ".database-export.tar",
    ".sql-export.zip", ".db-export.zip", ".database-export.zip",
    ".import.sql", ".import.db", ".import.dump", ".sql-import", ".db-import", ".database-import",
    ".import.sql.gz", ".import.db.gz", ".import.dump.gz", ".sql-import.gz", ".db-import.gz",
    ".database-import.gz", ".import.sql.bz2", ".import.db.bz2", ".import.dump.bz2", ".sql-import.bz2",
    ".db-import.bz2", ".database-import.bz2", ".import.sql.xz", ".import.db.xz", ".import.dump.xz",
    ".sql-import.xz", ".db-import.xz", ".database-import.xz", ".import.sql.zst", ".import.db.zst",
    ".import.dump.zst", ".sql-import.zst", ".db-import.zst", ".database-import.zst",
    ".import.sql.zip", ".import.db.zip", ".import.dump.zip", ".sql-import.zip", ".db-import.zip",
    ".database-import.zip",
    ".migrate.sql", ".migrate.db", ".migration.sql", ".migration.db", ".migrations.sql",
    ".migrations.db", ".sql-migrate", ".db-migrate", ".sql-migration", ".db-migration",
    ".sql-migrations", ".db-migrations", ".flyway.sql", ".flyway.db", ".flyway-migration",
    ".flyway-migrations", ".liquibase.sql", ".liquibase.db", ".liquibase-changelog",
    ".liquibase-changelog.sql", ".liquibase-changelog.db", ".db-migrator", ".db-migrator.sql",
    ".db-migrator.db", ".schema-migration", ".schema-migration.sql", ".schema-migration.db",
    ".data-migration", ".data-migration.sql", ".data-migration.db",
    ".change.sql", ".changes.sql", ".db-change", ".db-changes", ".sql-change", ".sql-changes",
    ".alter.sql", ".alteration.sql", ".modify.sql", ".modification.sql", ".update-schema.sql",
    ".update-schema.db", ".schema-update.sql", ".schema-update.db", ".schema-change.sql",
    ".schema-change.db", ".database-change.sql", ".database-change.db", ".ddl-change.sql",
    ".ddl-change.db", ".dml-change.sql", ".dml-change.db",
    ".validate.sql", ".validate.db", ".sql-validate", ".db-validate", ".validation.sql",
    ".validation.db", ".sql-validation", ".db-validation", ".check.sql", ".check.db",
    ".sql-check", ".db-check", ".verify.sql", ".verify.db", ".sql-verify", ".db-verify",
    ".integrity.sql", ".integrity.db", ".sql-integrity", ".db-integrity", ".consistency.sql",
    ".consistency.db", ".sql-consistency", ".db-consistency", ".referential.sql", ".referential.db",
    ".sql-referential", ".db-referential",
    ".test.sql", ".test.db", ".sql-test", ".db-test", ".tests.sql", ".tests.db", ".sql-tests",
    ".db-tests", ".unittest.sql", ".unittest.db", ".unit-test.sql", ".unit-test.db",
    ".integration-test.sql", ".integration-test.db", ".system-test.sql", ".system-test.db",
    ".e2e-test.sql", ".e2e-test.db", ".regression-test.sql", ".regression-test.db",
    ".performance-test.sql", ".performance-test.db", ".load-test.sql", ".load-test.db",
    ".stress-test.sql", ".stress-test.db", ".benchmark.sql", ".benchmark.db", ".sql-benchmark",
    ".db-benchmark", ".test-data.sql", ".test-data.db", ".fixture-data.sql", ".fixture-data.db",
    ".docs.sql", ".docs.db", ".sql-docs", ".db-docs", ".documentation.sql", ".documentation.db",
    ".sql-documentation", ".db-documentation", ".readme.sql", ".readme.db", ".sql-readme",
    ".db-readme", ".guide.sql", ".guide.db", ".sql-guide", ".db-guide", ".tutorial.sql",
    ".tutorial.db", ".sql-tutorial", ".db-tutorial", ".example.sql", ".example.db", ".sql-example",
    ".db-example", ".examples.sql", ".examples.db", ".sql-examples", ".db-examples", ".sample.sql",
    ".sample.db", ".sql-sample", ".db-sample", ".samples.sql", ".samples.db", ".sql-samples",
    ".db-samples", ".demo.sql", ".demo.db", ".sql-demo", ".db-demo", ".demos.sql", ".demos.db",
    ".sql-demos", ".db-demos",
    ".dev.sql", ".dev.db", ".sql-dev", ".db-dev", ".development.sql", ".development.db",
    ".sql-development", ".db-development", ".staging.sql", ".staging.db", ".sql-staging",
    ".db-staging", ".prod.sql", ".prod.db", ".sql-prod", ".db-prod", ".production.sql",
    ".production.db", ".sql-production", ".db-production", ".uat.sql", ".uat.db", ".sql-uat",
    ".db-uat", ".user-acceptance.sql", ".user-acceptance.db", ".qa.sql", ".qa.db", ".sql-qa",
    ".db-qa", ".quality-assurance.sql", ".quality-assurance.db", ".sandbox.sql", ".sandbox.db",
    ".sql-sandbox", ".db-sandbox", ".playground.sql", ".playground.db", ".sql-playground",
    ".db-playground", ".scratch.sql", ".scratch.db", ".sql-scratch", ".db-scratch",
    ".sql.gpg", ".db.gpg", ".dump.gpg", ".sql.pgp", ".db.pgp", ".dump.pgp", ".sql.asc",
    ".db.asc", ".dump.asc", ".sql.age", ".db.age", ".dump.age", ".sql.age.enc", ".db.age.enc",
    ".dump.age.enc", ".sql.encrypted.gpg", ".db.encrypted.gpg", ".dump.encrypted.gpg",
    ".sql.encrypted.pgp", ".db.encrypted.pgp", ".dump.encrypted.pgp", ".sql.crypt.gpg",
    ".db.crypt.gpg", ".dump.crypt.gpg", ".sql.secure.gpg", ".db.secure.gpg", ".dump.secure.gpg",
    ".recovery.sql", ".recovery.db", ".sql-recovery", ".db-recovery", ".recover.sql", ".recover.db",
    ".sql-recover", ".db-recover", ".restore.sql", ".restore.db", ".sql-restore", ".db-restore",
    ".restoration.sql", ".restoration.db", ".sql-restoration", ".db-restoration", ".repair.sql",
    ".repair.db", ".sql-repair", ".db-repair", ".fix.sql", ".fix.db", ".sql-fix", ".db-fix",
    ".corrupt.sql", ".corrupt.db", ".sql-corrupt", ".db-corrupt", ".corruption.sql", ".corruption.db",
    ".sql-corruption", ".db-corruption", ".damaged.sql", ".damaged.db", ".sql-damaged", ".db-damaged",
    ".sensitive-sql", ".sensitive-db", ".sensitive-dump", ".confidential-sql", ".confidential-db",
    ".confidential-dump", ".private-sql", ".private-db", ".private-dump", ".secret-sql", ".secret-db",
    ".secret-dump", ".classified-sql", ".classified-db", ".classified-dump", ".restricted-sql",
    ".restricted-db", ".restricted-dump", ".proprietary-sql", ".proprietary-db", ".proprietary-dump",
    ".internal-sql", ".internal-db", ".internal-dump", ".company-sql", ".company-db", ".company-dump",
    ".corporate-sql", ".corporate-db", ".corporate-dump", ".financial-sql", ".financial-db",
    ".financial-dump", ".customer-sql", ".customer-db", ".customer-dump", ".client-sql", ".client-db",
    ".client-dump", ".user-sql", ".user-db", ".user-dump", ".userdata-sql", ".userdata-db",
    ".userdata-dump", ".personal-sql", ".personal-db", ".personal-dump",
    ".vintage-sql", ".vintage-db", ".legacy-sql", ".legacy-db", ".legacy-dump", ".old-sql",
    ".old-db", ".old-dump", ".archive-sql", ".archive-db", ".archive-dump", ".obsolete-sql",
    ".obsolete-db", ".obsolete-dump", ".deprecated-sql", ".deprecated-db", ".deprecated-dump",
    ".historical-sql", ".historical-db", ".historical-dump", ".classic-sql", ".classic-db",
    ".classic-dump", ".retro-sql", ".retro-db", ".retro-dump", ".ancient-sql", ".ancient-db",
    ".ancient-dump", ".original-sql", ".original-db", ".original-dump", ".master-sql", ".master-db",
    ".master-dump", ".primary-sql", ".primary-db", ".primary-dump", ".source-sql", ".source-db",
    ".source-dump",
    ".distributed-sql", ".distributed-db", ".distributed-dump", ".sharded-sql", ".sharded-db",
    ".sharded-dump", ".partitioned-sql", ".partitioned-db", ".partitioned-dump", ".cluster-sql",
    ".cluster-db", ".cluster-dump", ".replicated-sql", ".replicated-db", ".replicated-dump",
    ".federated-sql", ".federated-db", ".federated-dump", ".distributed-sql-dump", ".distributed-db-dump",
    ".global-sql", ".global-db", ".global-dump", ".regional-sql", ".regional-db", ".regional-dump",
    ".blockchain-sql", ".blockchain-db", ".blockchain-dump", ".ethereum-sql", ".ethereum-db",
    ".ethereum-dump", ".bitcoin-sql", ".bitcoin-db", ".bitcoin-dump", ".crypto-sql", ".crypto-db",
    ".crypto-dump", ".web3-sql", ".web3-db", ".web3-dump", ".smart-contract-sql", ".smart-contract-db",
    ".smart-contract-dump", ".defi-sql", ".defi-db", ".defi-dump", ".nft-sql", ".nft-db", ".nft-dump",
    ".token-sql", ".token-db", ".token-dump", ".wallet-sql", ".wallet-db", ".wallet-dump",
    ".ml-sql", ".ml-db", ".ml-dump", ".ai-sql", ".ai-db", ".ai-dump", ".machine-learning-sql",
    ".machine-learning-db", ".machine-learning-dump", ".data-science-sql", ".data-science-db",
    ".data-science-dump", ".analytics-sql", ".analytics-db", ".analytics-dump", ".bigdata-sql",
    ".bigdata-db", ".bigdata-dump", ".datamining-sql", ".datamining-db", ".datamining-dump",
    ".predictive-sql", ".predictive-db", ".predictive-dump", ".forecasting-sql", ".forecasting-db",
    ".forecasting-dump", ".recommendation-sql", ".recommendation-db", ".recommendation-dump",
}
