vulnerable_extensions = {
    ".pem", ".key", ".priv", ".private", ".secret", ".id_rsa", ".id_dsa",
    ".id_ecdsa", ".id_ecdsa_sk", ".id_ed25519", ".id_ed25519_sk", ".id_xmss",
    ".identity", ".ppk", ".ssh_host_rsa_key", ".ssh_host_dsa_key",
    ".ssh_host_ecdsa_key", ".ssh_host_ed25519_key", ".ssh_host_key",
    ".authorized_keys", ".authorized_keys2", ".ssh_private_key", ".ssh_private_key.pub",
    ".putty_private_key", ".pageant.ppk", ".pageant_key", ".pageant_keys",
    ".winscp_private", ".filezilla_private", ".jks", ".keystore", ".truststore",
    ".bks", ".p12", ".pfx", ".pkcs12", ".p8", ".pkcs8", ".pem-key", ".pem-crt",
    ".key-pem", ".crt-pem", ".ssl-key", ".tls-key", ".x509-key", ".privkey",
    ".certkey", ".combined", ".privkey.pem", ".privkey.crt", ".privkey.der",
    ".privkey.p12", ".privkey.pfx", ".privkey.jks", ".certkey.pem", ".certkey.crt",
    ".certkey.der", ".certkey.p12", ".certkey.pfx", ".combined.pem", ".combined.crt",
    ".combined.der", ".combined.p12", ".combined.pfx", ".ovpn", ".openvpn.key",
    ".openvpn.crt", ".openvpn.pem", ".openvpn.der", ".openvpn.p12", ".openvpn.pfx",
    ".openvpn.client.key", ".openvpn.server.key", ".openvpn.tls-auth.key",
    ".openvpn.tls-crypt.key", ".openvpn.auth-file", ".openvpn.auth-file.pass",
    ".openvpn.auth-file.password", ".openvpn.auth-file.creds", ".wireguard.key",
    ".wireguard.priv", ".wireguard.private", ".wireguard.psk", ".wireguard.preshared",
    ".wireguard.preshared.key", ".wireguard.preshared.psk", ".wireguard.peer.key",
    ".wireguard.peer.priv", ".wireguard.peer.private", ".wireguard.peer.psk",
    ".wireguard.endpoint.key", ".wireguard.endpoint.priv", ".ipsec.secrets",
    ".ipsec.secrets.key", ".ipsec.secrets.pem", ".ipsec.psk", ".ipsec.preshared",
    ".ipsec.preshared.key", ".ipsec.preshared.psk", ".ipsec.user.psk",
    ".strongswan.secrets", ".strongswan.secrets.key", ".swanctl.secrets",
    ".swanctl.secrets.key", ".gpg", ".pgp", ".secring", ".gpg-sec", ".pgp-sec",
    ".private-keys-v1.d", ".gpg2.private-keys-v1.d", ".gpg2.private-keys",
    ".gnupg.private-keys-v1.d", ".keyring", ".pubring", ".secring", ".kbx-key",
    ".kbx-secret", ".gpg-agent", ".gpg-agent.ssh", ".gpg-agent.ssh-control",
    ".keytab", ".krb5.keytab", ".krb5keytab", ".service.keytab", ".host.keytab",
    ".user.keytab", ".krb5kt", ".ccache", ".credentials-cache", ".tgt",
    ".k5identity", ".k5login", ".k5users", ".kdc.conf", ".krb5.conf", ".kadm5.acl",
    ".kdbx", ".keepass", ".keepass2", ".keepassx", ".1password", ".1pif",
    ".agilekeychain", ".opvault", ".dashlane", ".lastpass", ".bitwarden", ".vault",
    ".vaultpass", ".kdb", ".ec", ".ecdsa", ".dsa", ".rsa", ".ed25519", ".ed448",
    ".xmss", ".sphincs", ".bls12381", ".curve25519", ".curve448", ".p256", ".p384",
    ".p521", ".secp256k1", ".secp256r1", ".x25519", ".x448", ".rsa.key",
    ".rsa.priv", ".dsa.key", ".dsa.priv", ".ec.key", ".ec.priv", ".ecdsa.key",
    ".ecdsa.priv", ".ed25519.key", ".ed25519.priv", ".ed448.key", ".ed448.priv",
    ".x25519.key", ".x25519.priv", ".x448.key", ".x448.priv", ".curve25519.key",
    ".curve25519.priv", ".pkcs1", ".pkcs8.encrypted", ".openssl.key", ".ssl.key",
    ".tls.key", ".x509.key", ".ca-key", ".ca.pem", ".ca.der", ".ca.p12", ".ca.pfx",
    ".ca-chain.key", ".ca-bundle.key", ".root-ca.key", ".intermediate-ca.key",
    ".issuer-ca.key", ".fullchain.key", ".bundle.key", ".ovpn.key", ".ovpn.crt",
    ".ovpn.pem", ".openvpn.ca", ".openvpn.dh", ".openvpn.tls-auth", ".openvpn.tls-crypt",
    ".wireguard.conf", ".wireguard.config", ".wireguard.wg", ".wireguard.wg0.conf",
    ".wireguard.allowed-ips", ".wireguard.peer.conf", ".wireguard.peer.config",
    ".wireguard.endpoint.conf", ".ipsec.conf", ".ipsec.config", ".strongswan.conf",
    ".strongswan.config", ".swanctl.conf", ".swanctl.config", ".ipsec.secrets.keystore",
    ".ipsec.secrets.truststore", ".strongswan.secrets.keystore", ".swanctl.secrets.keystore",
    ".gnupg", ".gnupg.conf", ".gnupg.keyring", ".gnupg.pubring", ".gnupg.secring",
    ".gnupg.kbx", ".gnupg.trustdb", ".gpg.conf", ".gpg-agent.conf", ".dirmngr.conf",
    ".pgp2", ".pgp2.sec", ".pgp6", ".pgp6.sec", ".jceks", ".jck", ".cacerts",
    ".jssecacerts", ".keychain", ".keychain-db", ".login.keychain", ".system.keychain",
    ".keyring-store", ".keyring-db", ".jks.enc", ".keystore.enc", ".truststore.enc",
    ".bks.enc", ".p12.enc", ".pfx.enc", ".pem.bak", ".key.bak", ".priv.bak",
    ".private.bak", ".secret.bak", ".id_rsa.bak", ".ppk.bak", ".jks.bak",
    ".keystore.bak", ".truststore.bak", ".p12.bak", ".pfx.bak", ".ovpn.bak",
    ".wireguard.key.bak", ".ipsec.secrets.bak", ".gpg.bak", ".keytab.bak",
    ".kdbx.bak", ".1password.bak", ".old", ".old1", ".old2", ".old3", ".old4",
    ".old5", ".old6", ".old7", ".old8", ".old9", ".old10", ".bak1", ".bak2",
    ".bak3", ".bak4", ".bak5", ".bak6", ".bak7", ".bak8", ".bak9", ".bak10",
    ".backup1", ".backup2", ".backup3", ".backup4", ".backup5", ".backup6",
    ".backup7", ".backup8", ".backup9", ".backup10", ".save1", ".save2", ".save3",
    ".save4", ".save5", ".save6", ".save7", ".save8", ".save9", ".save10",
    ".1", ".2", ".3", ".4", ".5", ".6", ".7", ".8", ".9", ".10", ".v1", ".v2",
    ".v3", ".v4", ".v5", ".v6", ".v7", ".v8", ".v9", ".v10", ".ver1", ".ver2",
    ".ver3", ".ver4", ".ver5", ".ver6", ".ver7", ".ver8", ".ver9", ".ver10",
    ".sensitive", ".sensitive.enc", ".sensitive.encrypted", ".sensitive.secure",
    ".confidential", ".confidential.enc", ".confidential.encrypted",
    ".private-data", ".private-data.enc", ".private-data.encrypted",
    ".secure-data", ".secure-data.enc", ".encrypted-data", ".encrypted-data.enc",
    ".ssh_agent", ".ssh_agent_sock", ".ssh_control", ".ssh_control_master",
    ".ssh_environment", ".ssh_rc", ".ssh_askpass", ".ssh_askpass.conf",
    ".known_hosts", ".known_hosts2", ".ssh_config", ".sshd_config", ".ssh2_config",
    ".putty_config", ".pageant", ".winscp", ".filezilla", ".filezilla.xml",
    ".filezilla.xml.encrypted", ".putty_session", ".putty_sessions", ".putty_known_hosts",
    ".winscp.ini", ".winscp_session", ".filezilla_session", ".crt", ".cer",
    ".cert", ".der", ".p7b", ".p7c", ".csr", ".crtx", ".certificate", ".certificates",
    ".chain", ".fullchain", ".bundle", ".intermediate", ".root", ".issuer",
    ".ca-chain", ".ca-certificates", ".ca-bundle", ".intermediate-ca", ".root-ca",
    ".cert-chain", ".ssl-cert", ".tls-cert", ".x509-cert", ".x509", ".pem-crt",
    ".crt-pem", ".ovpn.crt", ".openvpn.crt", ".openvpn.server.crt", ".openvpn.client.crt",
    ".wireguard.pub", ".wireguard.public", ".ipsec.crt", ".strongswan.crt",
    ".swanctl.crt", ".gpg-pub", ".pgp-pub", ".pubring", ".gnupg.pubring",
    ".ssh_public_key", ".ssh_host_rsa_key.pub", ".ssh_host_ecdsa_key.pub",
    ".ssh_host_ed25519_key.pub", ".identity.pub", ".authorized_keys.pub",
    ".rsa.pub", ".dsa.pub", ".ec.pub", ".ecdsa.pub", ".ed25519.pub", ".ed448.pub",
    ".x25519.pub", ".x448.pub", ".curve25519.pub", ".pgp-pub", ".pgp2.pub",
    ".pgp6.pub", ".key.pub", ".ssh2_hostkey", ".ssh2_hostkey.pub", ".ssh2_public",
    ".putty_public_key", ".winscp_public", ".filezilla_public", ".pub",
}
