linux_ignore = {
    "/bin", "/boot", "/dev", "/etc", "/lib", "/lib64", "/proc",
    "/sbin", "/sys", "/usr", "/var", "/run", "/lost+found",
    "/usr/bin", "/usr/sbin", "/usr/lib", "/usr/lib64", "/usr/libexec",
    "/usr/share", "/usr/include", "/usr/src", "/usr/local/bin", "/usr/local/sbin",
    "/usr/local/lib", "/usr/local/lib64", "/usr/local/libexec", "/usr/local/share",
    "/usr/local/include", "/usr/local/src", "/usr/games", "/usr/games/bin",
    "/usr/games/lib", "/usr/games/share", "/usr/games/src",
    "/var/log", "/var/cache", "/var/tmp", "/var/run", "/var/lock",
    "/var/spool", "/var/mail", "/var/opt", "/var/crash", "/var/local",
    "/var/account", "/var/games", "/var/empty", "/var/lib/apt/lists",
    "/var/lib/dpkg", "/var/lib/rpm", "/var/lib/yum", "/var/lib/pacman",
    "/var/lib/zypp", "/var/lib/portage", "/var/log/apt", "/var/log/yum.log",
    "/var/log/dpkg.log", "/var/log/rpm.log", "/var/log/pacman.log",
    "/var/log/zypp.log", "/var/log/portage.log", "/var/log/syslog",
    "/var/log/messages", "/var/log/kern.log", "/var/log/auth.log",
    "/var/log/secure", "/var/log/maillog", "/var/log/mail.log",
    "/var/log/cron", "/var/log/dmesg", "/var/log/boot.log",
    "/etc/alternatives", "/etc/cron.d", "/etc/cron.daily", "/etc/cron.hourly",
    "/etc/cron.monthly", "/etc/cron.weekly", "/etc/default", "/etc/init.d",
    "/etc/ld.so.conf.d", "/etc/logrotate.d", "/etc/modprobe.d",
    "/etc/modules-load.d", "/etc/network", "/etc/NetworkManager",
    "/etc/opt", "/etc/profile.d", "/etc/rc0.d", "/etc/rc1.d", "/etc/rc2.d",
    "/etc/rc3.d", "/etc/rc4.d", "/etc/rc5.d", "/etc/rc6.d", "/etc/rcS.d",
    "/etc/skel", "/etc/sysconfig", "/etc/systemd", "/etc/udev",
    "/etc/X11", "/etc/xdg",
    "/proc/sys", "/proc/bus", "/proc/driver", "/proc/fs", "/proc/irq",
    "/proc/tty", "/proc/sysvipc", "/proc/self", "/proc/thread-self",
    "/sys/block", "/sys/bus", "/sys/class", "/sys/dev", "/sys/devices",
    "/sys/firmware", "/sys/fs", "/sys/kernel", "/sys/module",
    "/sys/power",
    "/dev/block", "/dev/char", "/dev/disk", "/dev/dri", "/dev/fd",
    "/dev/input", "/dev/mapper", "/dev/net", "/dev/shm", "/dev/tty",
    "/tmp", "/var/tmp", "/dev/shm", "/run/lock", "/run/shm",
    "/run/user", "/var/run/user", "/tmp/.X11-unix", "/tmp/.XIM-unix",
    "/tmp/.font-unix", "/tmp/.ICE-unix", "/tmp/.Test-unix",
    "/var/cache/apt", "/var/cache/apt/archives", "/var/cache/apt/archives/partial",
    "/var/cache/dnf", "/var/cache/yum", "/var/cache/pacman/pkg",
    "/var/cache/zypp/packages", "/var/cache/portage", "/var/cache/fontconfig",
    "/var/cache/ldconfig", "/var/cache/man", "/var/cache/debconf",
    "/var/cache/logwatch", "/var/cache/cracklib", "/var/cache/cups",
    "/var/log/apt", "/var/log/installer", "/var/log/unattended-upgrades",
    "/var/log/fsck", "/var/log/news", "/var/log/old", "/var/log/samba",
    "/var/log/setup", "/var/log/squid", "/var/log/swtpm", "/var/log/tallylog",
    "/var/log/teamviewer", "/var/log/wtmp", "/var/log/btmp", "/var/log/lastlog",
    "/var/log/faillog", "/var/log/audit", "/var/log/journal",
    "/lib/firmware", "/lib/modules", "/lib/udev", "/lib/systemd",
    "/lib64/firmware", "/lib64/modules", "/lib64/udev", "/lib64/systemd",
    "/usr/lib/firmware", "/usr/lib/modules", "/usr/lib/udev", "/usr/lib/systemd",
    "/usr/lib64/firmware", "/usr/lib64/modules", "/usr/lib64/udev", "/usr/lib64/systemd",
    "/boot/grub", "/boot/efi", "/boot/loader", "/boot/dtb",
    "/etc/grub.d", "/etc/default/grub", "/usr/lib/grub",
    "/var/lib/docker", "/var/lib/containerd", "/var/lib/lxc",
    "/var/lib/libvirt", "/var/lib/lxd", "/var/lib/snapd",
    "/var/lib/flatpak", "/var/lib/snapd/hostfs",
    "/var/lib/apt", "/var/lib/dpkg", "/var/lib/rpm", "/var/lib/yum",
    "/var/lib/pacman", "/var/lib/zypp", "/var/lib/portage",
    "/usr/lib/systemd", "/etc/systemd", "/run/systemd",
    "/var/lib/systemd", "/usr/lib/systemd/user", "/etc/systemd/user",
    "/usr/share/dbus-1", "/etc/dbus-1", "/run/dbus",
    "/usr/share/polkit-1", "/etc/polkit-1", "/var/lib/polkit-1",
    "/usr/lib/udev", "/etc/udev", "/run/udev",
    "/etc/selinux", "/etc/apparmor.d", "/sys/fs/selinux",
    "/sys/kernel/security/apparmor",
    "/etc/pam.d", "/lib/security", "/lib64/security",
    "/usr/lib/security", "/usr/lib64/security",
    "/usr/share/locale", "/usr/share/i18n", "/usr/lib/locale",
    "/var/lib/locales", "/etc/locale.gen",
    "/usr/share/man", "/usr/share/info", "/usr/share/doc",
    "/usr/share/help", "/usr/share/gtk-doc",
    "/usr/share/terminfo", "/etc/terminfo", "/lib/terminfo",
    "/usr/share/mime", "/etc/mime.types",
    "/etc/ssl/certs", "/usr/share/ca-certificates",
    "/var/lib/ca-certificates", "/etc/pki",
    "/usr/src/linux-headers", "/usr/src/linux-source",
    "/usr/lib/debug", "/usr/lib64/debug",
    "/usr/share/games", "/var/games",
    "/var/spool/cron", "/var/spool/at", "/var/spool/lpd",
    "/var/spool/mqueue", "/var/spool/postfix", "/var/spool/smtpd",
    "/var/mail", "/var/spool/mail",
    "/var/lock", "/run/lock",
    "/var/log/journal", "/run/log/journal",
    "/var/crash", "/var/lib/systemd/coredump",
    "/snap", "/var/lib/snapd", "/snap/bin",
    "/var/lib/flatpak", "/usr/share/flatpak",
    "/home/*/.cache/AppImage",
    "/sys/fs/cgroup",
    "/sys/fs/pstore",
    "/sys/kernel/debug",
    "/sys/kernel/security",
    "/dev/pts",
    "/dev/bus",
    "/dev/cpu",
    "/dev/loop-control",
    "/dev/mem",
    "/dev/port",
    "/dev/raw",
    "/dev/rtc",
    "/dev/snd",
    "/dev/usb",
    "/run/log",
    "/run/lvm",
    "/run/mount",
    "/run/NetworkManager",
    "/run/sendsigs.omit.d",
    "/run/sysctl.d",
    "/run/tmpfiles.d",
    "/var/backups",
    "/var/yp",
    "/var/lib/machines",
    "/var/lib/misc",
    "/var/lib/nfs",
    "/var/lib/urandom",
    "/var/lib/usbutils",
    "/var/lib/vim",
    "/var/lib/xkb",
    "/boot/config",
    "/boot/initrd.img",
    "/boot/vmlinuz",
    "/boot/System.map",
    "/etc/fonts",
    "/etc/gconf",
    "/etc/gtk-2.0",
    "/etc/gtk-3.0",
    "/usr/lib/tmpfiles.d",
    "/usr/lib/modules-load.d",
    "/usr/lib/sysctl.d",
    "/usr/lib/NetworkManager",
    "/usr/lib/python3",
    "/usr/lib/python2",
    "/usr/lib/perl5",
    "/usr/lib/ruby",
    "/usr/lib/jvm",
    "/usr/lib/llvm",
    "/usr/lib/gcc",
    "/usr/lib/x86_64-linux-gnu",
    "/var/lib/rancher",
}       
