macos_ignore = {
    "/System", "/System/Library", "/System/Library/CoreServices", "/System/Library/Extensions",
    "/System/Library/Frameworks", "/System/Library/PrivateFrameworks", "/System/Library/Kernels",
    "/System/Library/LaunchDaemons", "/System/Library/LaunchAgents", "/System/Library/User Template",
    "/System/Library/Speech", "/System/Library/Sounds", "/System/Library/Perl",
    "/System/Library/OpenSSL", "/System/Library/PasswordServer", "/System/Library/Python",
    "/System/Library/Ruby", "/System/Library/ScriptingAdditions", "/System/Library/Security",
    "/System/Library/ServerSetup", "/System/Library/Services", "/System/Library/StartupItems",
    "/System/Library/SystemConfiguration", "/System/Library/TextEncodings", "/System/Library/UserConfigurationProfiles",
    "/System/Library/Extensions", "/Library/Extensions", "/System/Library/IOKit",
    "/System/Library/IOPlatformPluginFamily", "/System/Library/IOUSBHostFamily",
    "/tmp", "/private/tmp", "/var/tmp", "/private/var/tmp", "/var/folders",
    "/private/var/folders", "/System/Library/Caches", "/Library/Caches",
    "/private/var/vm", "/private/var/log", "/var/log", "/private/var/run",
    "/var/log", "/private/var/log", "/Library/Logs", "/System/Library/Logs",
    "/var/log/asl", "/var/log/install.log", "/var/log/system.log",
    "/var/log/wifi.log", "/var/log/apache2", "/var/log/mail",
    "/Applications/Utilities", "/System/Applications", "/System/Applications/Utilities",
    "/Applications/Safari.app", "/Applications/Mail.app", "/Applications/Calendar.app",
    "/Applications/Contacts.app", "/Applications/Notes.app", "/Applications/Reminders.app",
    "/Applications/Messages.app", "/Applications/FaceTime.app", "/Applications/Photo Booth.app",
    "/Applications/Preview.app", "/Applications/TextEdit.app", "/Applications/QuickTime Player.app",
    "/System/Library/Frameworks/AppKit.framework", "/System/Library/Frameworks/Foundation.framework",
    "/System/Library/Frameworks/CoreFoundation.framework", "/System/Library/Frameworks/CoreGraphics.framework",
    "/System/Library/Frameworks/CoreImage.framework", "/System/Library/Frameworks/CoreServices.framework",
    "/System/Library/Frameworks/IOKit.framework", "/System/Library/Frameworks/Kernel.framework",
    "/System/Library/Frameworks/Security.framework", "/System/Library/Frameworks/SystemConfiguration.framework",
    "/System/Library/Frameworks/WebKit.framework", "/System/Library/Frameworks/JavaScriptCore.framework",
    "/Applications/Xcode.app", "/Library/Developer", "/Developer",
    "/Applications/Xcode-beta.app", "/Library/Apple/usr/libexec",
    "/Library/Caches/com.apple.helpd", "/Library/Caches/com.apple.helpviewer",
    "/System/Library/Caches/com.apple.CVMS", "/System/Library/Caches/com.apple.coreduetd",
    "/System/Library/Caches/com.apple.IntlDataCache", "/System/Library/Caches/com.apple.kext.caches",
    "/System/Library/Fonts", "/Library/Fonts", "/Network/Library/Fonts",
    "/System/Library/Fonts/Supplemental", "/System/Library/AssetsV2/com_apple_MobileAsset_Font5",
    "/System/Library/PreferencePanes", "/Library/PreferencePanes",
    "/System/Library/QuickLook", "/Library/QuickLook",
    "/System/Library/Spotlight", "/Library/Spotlight",
    "/System/Library/Automator", "/Library/Automator",
    "/Applications/GarageBand.app", "/Applications/iMovie.app",
    "/Applications/Keynote.app", "/Applications/Numbers.app", "/Applications/Pages.app",
    "/usr/libexec", "/usr/bin", "/usr/sbin", "/bin", "/sbin",
    "/etc", "/private/etc", "/var", "/private/var", "/opt",
    "/Library/InstallerSandboxes", "/Library/InstallerSandboxes/.PKInstallSandboxManager",
    "/Library/Updates", "/private/var/folders/zz",
    "/System/Library/PrivateFrameworks/PassKitCore.framework",
    "/System/Library/Assistant", "/System/Library/PrivateFrameworks/Siri",
    "/Volumes/com.apple.TimeMachine.localsnapshots",
    "/System/Library/Caches/com.apple.apfs",
    "/System/Library/CoreServices/CoreAudio",
    "/Library/Preferences/SystemConfiguration",
    "/Library/Managed Preferences",
    "/System/Library/LaunchDaemons", "/Library/LaunchDaemons",
    "/System/Library/LaunchAgents", "/Library/LaunchAgents",
    "/System/Installation", "/System/Installation/Packages",
    "/private/var/db/com.apple.xpc.launchd", "/private/var/db/ConfigurationProfiles",
    "/System/Library/PrivateFrameworks/AppleTVServices.framework",
    "/Users/Shared/SC Info", "/Library/Application Support/Apple",
    "/Library/Application Support/CrashReporter", "/Library/Application Support/Radio",
    "/System/Library/CoreServices/Applications",
    "/System/Library/CoreServices/Finder.app",
    "/System/Library/CoreServices/Menu Extras",
    "/System/Library/CoreServices/Software Update.app",
    "/Library/Preferences/Logging",
    "/Library/Preferences/OpenDirectory",
    "/Library/Preferences/Security",
    "/private/var/at",
    "/private/var/audit",
    "/private/var/backups",
    "/private/var/db/dhcpclient",
    "/private/var/db/dyld",
    "/private/var/db/mds",
    "/private/var/db/softwareupdate",
    "/private/var/db/com.apple.security.sandbox",
    "/private/var/db/caches",
    "/private/var/db/diagnostics",
    "/private/var/db/locationd",
    "/private/var/db/netinstall",
    "/private/var/db/powerlog",
    "/private/var/db/uuidtext",
    "/private/var/run/syslog",
    "/private/var/run/mDNSResponder",
    "/private/var/run/opendirectoryd",
    "/usr/lib",
    "/usr/lib/pam",
    "/usr/lib/security",
    "/usr/lib/ssl",
    "/usr/lib/cgi-bin",
    "/usr/lib/php",
    "/usr/lib/perl5",
    "/usr/lib/ruby",
    "/usr/lib/python3",
    "/usr/lib/jvm",
    "/Network/Library",
    "/Network/Library/Preferences",
    "/Network/Library/Fonts",
    "/Network/Library/Application Support",
    "/cores",
    "/System/Volumes/Data",
    "/System/Volumes/Preboot",
    "/System/Volumes/Update",
    "/System/Volumes/VM",

}