windows_ignore = {
    "C:\\Windows", "C:\\Windows\\System32", "C:\\Windows\\System", "C:\\Windows\\SysWOW64",
    "C:\\Windows\\WinSxS", "C:\\Windows\\Installer", "C:\\Windows\\Microsoft.NET",
    "C:\\Windows\\Assembly", "C:\\Windows\\Globalization", "C:\\Windows\\Help",
    "C:\\Windows\\IME", "C:\\Windows\\INF", "C:\\Windows\\L2Schemas",
    "C:\\Windows\\LiveKernelReports", "C:\\Windows\\Logs", "C:\\Windows\\Media",
    "C:\\Windows\\ModemLogs", "C:\\Windows\\Performance", "C:\\Windows\\PLA",
    "C:\\Windows\\PolicyDefinitions", "C:\\Windows\\Prefetch", "C:\\Windows\\PrintDialog",
    "C:\\Windows\\Provisioning", "C:\\Windows\\Registration", "C:\\Windows\\RemotePackages",
    "C:\\Windows\\rescache", "C:\\Windows\\Resources", "C:\\Windows\\schemas",
    "C:\\Windows\\Security", "C:\\Windows\\ServiceProfiles", "C:\\Windows\\ServiceState",
    "C:\\Windows\\Servicing", "C:\\Windows\\Setup", "C:\\Windows\\ShellComponents",
    "C:\\Windows\\ShellExperiences", "C:\\Windows\\SKB", "C:\\Windows\\Speech",
    "C:\\Windows\\SystemResources", "C:\\Windows\\SysWOW64", "C:\\Windows\\TAPI",
    "C:\\Windows\\Tasks", "C:\\Windows\\Temp", "C:\\Windows\\tracing",
    "C:\\Windows\\Vss", "C:\\Windows\\Web", "C:\\Windows\\WinStore",
    "C:\\Windows\\WLXPGSnapshot", "C:\\Windows\\winsxs",
    "C:\\Temp", "C:\\Tmp", "C:\\Windows\\Temp", "C:\\Users\\Public\\Temp",
    "C:\\Users\\Default\\AppData\\Local\\Temp", "C:\\Users\\All Users\\Temp",
    "C:\\ProgramData\\Temp", "C:\\Windows\\Logs", "C:\\Windows\\Panther",
    "C:\\Windows\\SoftwareDistribution\\Download", "C:\\Windows\\SoftwareDistribution\\DataStore",
    "C:\\Windows\\System32\\LogFiles", "C:\\Windows\\System32\\Wbem\\Logs",
    "C:\\Windows\\System32\\Tasks", "C:\\Windows\\System32\\config\\systemprofile\\AppData\\Local\\Temp",
    "C:\\Windows\\SysWOW64\\config\\systemprofile\\AppData\\Local\\Temp",
    "C:\\Windows\\CSC", "C:\\Windows\\Downloaded Program Files",
    "C:\\Windows\\Fonts", "C:\\Windows\\Offline Web Pages",
    "C:\\ProgramData\\Microsoft\\Windows\\Caches", "C:\\ProgramData\\Microsoft\\Windows\\WER",
    "C:\\ProgramData\\Microsoft\\Windows\\DeviceMetadataCache", "C:\\ProgramData\\Microsoft\\Windows\\GameExplorer",
    "C:\\ProgramData\\Microsoft\\Windows\\NetCache", "C:\\ProgramData\\Microsoft\\Windows\\Ringtones",
    "C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\Accessibility",
    "C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\Administrative Tools",
    "C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\Maintenance",
    "C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\System Tools",
    "C:\\Windows\\System32\\DriverStore", "C:\\Windows\\System32\\DRIVERS",
    "C:\\Windows\\System32\\Drivers", "C:\\Windows\\System32\\DriverState",
    "C:\\Windows\\System32\\DriverStock", "C:\\Windows\\System32\\CatRoot",
    "C:\\Windows\\System32\\CatRoot2", "C:\\Windows\\INF",
    "C:\\Program Files\\Microsoft Office\\Office16\\ODF",
    "C:\\Program Files\\Microsoft Office\\Office16\\PPTW",
    "C:\\Program Files\\Microsoft Office\\root\\vfs\\ProgramFilesCommonX64\\Microsoft Shared\\EQUATION",
    "C:\\Program Files (x86)\\Microsoft Office\\root\\vfs\\ProgramFilesCommonX86\\Microsoft Shared\\EQUATION",
    "C:\\Windows\\Microsoft.NET\\Framework\\v1.0.3705\\Temporary ASP.NET Files",
    "C:\\Windows\\Microsoft.NET\\Framework\\v1.1.4322\\Temporary ASP.NET Files",
    "C:\\Windows\\Microsoft.NET\\Framework\\v2.0.50727\\Temporary ASP.NET Files",
    "C:\\Windows\\Microsoft.NET\\Framework\\v3.0\\Temporary ASP.NET Files",
    "C:\\Windows\\Microsoft.NET\\Framework\\v3.5\\Temporary ASP.NET Files",
    "C:\\Windows\\Microsoft.NET\\Framework\\v4.0.30319\\Temporary ASP.NET Files",
    "C:\\Windows\\Microsoft.NET\\Framework64\\v2.0.50727\\Temporary ASP.NET Files",
    "C:\\Windows\\Microsoft.NET\\Framework64\\v3.0\\Temporary ASP.NET Files",
    "C:\\Windows\\Microsoft.NET\\Framework64\\v3.5\\Temporary ASP.NET Files",
    "C:\\Windows\\Microsoft.NET\\Framework64\\v4.0.30319\\Temporary ASP.NET Files",
    "C:\\Program Files\\WindowsApps", "C:\\Program Files\\ModifiableWindowsApps",
    "C:\\Windows\\ImmersiveControlPanel", "C:\\Windows\\Camera",
    "C:\\Windows\\Containers", "C:\\Windows\\Cursors",
    "C:\\System Volume Information", "C:\\$Recycle.Bin", "C:\\$WinREAgent",
    "C:\\Windows\\System32\\Recovery", "C:\\Windows\\System32\\Restore",
    "C:\\Windows\\System32\\config\\TxR", "C:\\Windows\\System32\\config\\RegBack",
    "C:\\Windows\\System32\\config\\Journal", "C:\\Windows\\System32\\SMI\\Store\\Machine",
    "C:\\Windows\\System32\\SMI\\Store\\Machine\\SCHEMA", "C:\\Windows\\System32\\SMI\\Store\\Machine\\INDEX",
    "C:\\hiberfil.sys", "C:\\pagefile.sys", "C:\\swapfile.sys",
    "C:\\Windows\\SoftwareDistribution", "C:\\Windows\\System32\\SoftwareDistribution",
    "C:\\Windows\\WinSxS\\Backup", "C:\\Windows\\Installer\\$PatchCache$",
    "C:\\Users\\Default\\AppData\\Local\\Microsoft\\Windows\\Caches",
    "C:\\Users\\Default\\AppData\\Local\\Microsoft\\Windows\\Explorer",
    "C:\\Users\\Default\\AppData\\Local\\Microsoft\\Windows\\WER",
    "C:\\Users\\Default\\AppData\\Local\\Temp",
    "C:\\Users\\Default\\AppData\\Roaming\\Microsoft\\Windows\\Recent",
    "C:\\Users\\Public\\Documents\\My Videos",
    "C:\\Users\\Public\\Documents\\My Music",
    "C:\\Users\\Public\\Documents\\My Pictures",
    "C:\\Users\\Public\\Music\\Sample Music",
    "C:\\Users\\Public\\Pictures\\Sample Pictures",
    "C:\\Users\\Public\\Videos\\Sample Videos",
    "C:\\Users\\Public\\Recorded TV",
    "C:\\Users\\Public\\Libraries",
    "C:\\ProgramData\\Microsoft\\Windows Defender\\Definition Updates",
    "C:\\ProgramData\\Microsoft\\Windows Defender\\Scans",
    "C:\\ProgramData\\Microsoft\\Windows Defender\\Quarantine",
    "C:\\ProgramData\\Microsoft\\Windows Defender\\Support",
    "C:\\ProgramData\\Microsoft\\Windows Defender\\LocalCopy",
    "C:\\Users\\Default\\AppData\\Local\\Microsoft\\Edge\\User Data\\Default\\Cache",
    "C:\\Users\\Default\\AppData\\Local\\Microsoft\\Edge\\User Data\\Default\\Code Cache",
    "C:\\Users\\Default\\AppData\\Local\\Microsoft\\Edge\\User Data\\Default\\Service Worker\\CacheStorage",
    "C:\\Users\\Default\\AppData\\Local\\Microsoft\\Edge\\User Data\\Default\\Storage\\ext",
    "C:\\Users\\Default\\AppData\\Local\\Microsoft\\Internet Explorer\\CacheStorage",
    "C:\\Users\\Default\\AppData\\Local\\Microsoft\\Internet Explorer\\DOMStore",
    "C:\\ProgramData\\Microsoft\\Search", "C:\\ProgramData\\Microsoft\\Windows\\Search",
    "C:\\Windows\\System32\\Search", "C:\\Program Files\\Windows NT\\TableTextService",
    "C:\\Program Files\\Windows Mail", "C:\\Program Files (x86)\\Windows Mail",
    "C:\\Program Files\\Windows Media Player", "C:\\Program Files (x86)\\Windows Media Player",
    "C:\\Users\\Default\\AppData\\Local\\Microsoft\\Media Player",
    "C:\\Program Files\\Microsoft Silverlight", "C:\\Program Files (x86)\\Microsoft Silverlight",
    "C:\\Program Files\\Microsoft XNA", "C:\\Program Files (x86)\\Microsoft XNA",
    "C:\\Windows\\System32\\DirectX", "C:\\Windows\\SysWOW64\\DirectX",
    "C:\\Program Files\\Windows Photo Viewer", "C:\\Program Files (x86)\\Windows Photo Viewer",
    "C:\\Windows\\System32\\WindowsPortableDevices", "C:\\Windows\\SysWOW64\\WindowsPortableDevices",
    "C:\\Program Files\\Windows Sidebar", "C:\\Program Files (x86)\\Windows Sidebar",
    "C:\\Users\\Default\\AppData\\Local\\Microsoft\\Windows Sidebar",
    "C:\\Windows\\System32\\CardSpace", "C:\\Windows\\SysWOW64\\CardSpace",
    "C:\\Windows\\System32\\RMS", "C:\\Windows\\SysWOW64\\RMS",
    "C:\\Program Files\\Microsoft Sync Framework", "C:\\Program Files (x86)\\Microsoft Sync Framework",
    "C:\\Program Files\\Microsoft Antimalware", "C:\\Program Files (x86)\\Microsoft Antimalware",
    "C:\\Program Files\\Microsoft Security Client", "C:\\Program Files (x86)\\Microsoft Security Client",
    "C:\\Program Files\\Microsoft Office\\Office16\\lync.exe",
    "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\Modules\\PSReadLine\\SamplePSReadLineProfile.ps1",
    "C:\\Windows\\SysWOW64\\WindowsPowerShell\\v1.0\\Modules\\PSReadLine\\SamplePSReadLineProfile.ps1",
    "C:\\Windows\\System32\\spool",
    "C:\\Windows\\System32\\Printers",
    "C:\\Windows\\System32\\WinRM",
    "C:\\Windows\\System32\\Winevt",
    "C:\\Windows\\System32\\winevt\\Logs",
    "C:\\Windows\\System32\\GroupPolicy",
    "C:\\Windows\\System32\\GroupPolicyUsers",
    "C:\\Windows\\System32\\com",
    "C:\\Windows\\System32\\Dism",
    "C:\\Windows\\System32\\Eventvwr",
    "C:\\Windows\\System32\\FxsTmp",
    "C:\\Windows\\System32\\IIS",
    "C:\\Windows\\System32\\IISExpress",
    "C:\\Windows\\System32\\Inetsrv",
    "C:\\Windows\\System32\\Logs",
    "C:\\Windows\\System32\\MsDtc",
    "C:\\Windows\\System32\\Ntp",
    "C:\\Windows\\System32\\PerfMon",
    "C:\\Windows\\System32\\RAS",
    "C:\\Windows\\System32\\Remote",
    "C:\\Windows\\System32\\ResCache",
    "C:\\Windows\\System32\\Rpcnsh",
    "C:\\Windows\\System32\\RpcProxy",
    "C:\\Windows\\System32\\RTCOM",
    "C:\\Windows\\System32\\Scripting",
    "C:\\Windows\\System32\\ServerManager",
    "C:\\Windows\\System32\\Settings",
    "C:\\Windows\\System32\\srm",
    "C:\\Windows\\System32\\sru",
    "C:\\Windows\\System32\\sxs",
    "C:\\Windows\\System32\\SyncCenter",
    "C:\\Windows\\System32\\Sysprep",
    "C:\\Windows\\System32\\WaaS",
    "C:\\Windows\\System32\\Wallet",
    "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\Modules\\Pester",
    "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\Modules\\PackageManagement",
    "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\Modules\\PowerShellGet",
    "C:\\Windows\\System32\\wpr",
    "C:\\Windows\\System32\\WUDF",
    "C:\\Program Files\\Common Files",
    "C:\\Program Files\\Common Files\\Microsoft Shared",
    "C:\\Program Files\\Common Files\\Services",
    "C:\\Program Files\\Common Files\\System",
    "C:\\Program Files\\Internet Explorer",
    "C:\\Program Files\\Java",
    "C:\\Program Files\\Microsoft SQL Server",
    "C:\\Program Files\\MSBuild",
    "C:\\Program Files\\PackageManagement",
    "C:\\Program Files\\PowerShell",
    "C:\\Program Files\\Reference Assemblies",
    "C:\\Program Files\\Uninstall Information",
    "C:\\Program Files\\Windows NT",
    "C:\\Program Files\\Windows Security",
    "C:\\Program Files\\Windows Defender",
    "C:\\Program Files (x86)\\Common Files",
    "C:\\Program Files (x86)\\Internet Explorer",
    "C:\\Program Files (x86)\\Java",
    "C:\\Program Files (x86)\\Microsoft SQL Server",
    "C:\\Program Files (x86)\\MSBuild",
    "C:\\Program Files (x86)\\PackageManagement",
    "C:\\Program Files (x86)\\PowerShell",
    "C:\\Program Files (x86)\\Reference Assemblies",
    "C:\\Program Files (x86)\\Uninstall Information",
    "C:\\Program Files (x86)\\Windows NT",
    "C:\\Program Files (x86)\\Windows Defender",
    "C:\\ProgramData\\Microsoft\\Windows\\Start Menu",
    "C:\\ProgramData\\Microsoft\\Windows\\Templates",
    "C:\\ProgramData\\Microsoft\\Crypto",
    "C:\\ProgramData\\Microsoft\\Crypto\\RSA",
    "C:\\ProgramData\\Microsoft\\Crypto\\DSS",
    "C:\\ProgramData\\Microsoft\\Crypto\\Keys",
    "C:\\ProgramData\\Microsoft\\RAC",
    "C:\\ProgramData\\Microsoft\\RAC\\PublishedData",
    "C:\\ProgramData\\Microsoft\\RAC\\StateData",
    "C:\\ProgramData\\Microsoft\\RAC\\Temp",
    "C:\\ProgramData\\Microsoft\\Windows NT",
    "C:\\ProgramData\\Microsoft\\Windows NT\\MSFax",
    "C:\\ProgramData\\Microsoft\\XNA",
    "C:\\ProgramData\\Package Cache",
    "C:\\ProgramData\\regid.1991-06.com.microsoft",
    "C:\\ProgramData\\USOPrivate",
    "C:\\ProgramData\\USOShared",
    "C:\\ProgramData\\WindowsHolographicDevices",
    "C:\\Users\\Public\\AccountPictures",
    "C:\\Users\\Public\\Desktop",
    "C:\\Users\\Public\\Downloads",
    "C:\\Recovery",
    "C:\\$SysReset",
    "C:\\$Windows.~BT",
    "C:\\$Windows.~WS",
    "C:\\ESD",
    "C:\\Intel",
    "C:\\PerfLogs",
    "C:\\inetpub",
    "C:\\inetpub\\logs",
    "C:\\inetpub\\temp",
    "C:\\Program Files\\IIS",
    "C:\\Program Files\\IIS Express",
    "C:\\Windows\\System32\\LogFiles\\HTTPERR",
    "C:\\Windows\\System32\\LogFiles\\SCM",
    "C:\\Windows\\System32\\LogFiles\\SUM",
    "C:\\Windows\\System32\\LogFiles\\WMI",
    "C:\\Windows\\System32\\LogFiles\\Firewall",
    "C:\\Windows\\System32\\LogFiles\\Fax",
    "C:\\Windows\\System32\\LogFiles\\MSDTC",
    "C:\\Windows\\System32\\LogFiles\\SQM",
    "C:\\Program Files\\NVIDIA Corporation",
    "C:\\Program Files (x86)\\NVIDIA Corporation",
    "C:\\Program Files\\AMD",
    "C:\\Program Files (x86)\\AMD",
    "C:\\Program Files\\Intel",
    "C:\\Program Files (x86)\\Intel",
        }